Bug fix prep.sh, use is_available.sh in Makefiles
The prep.sh script printed incorrect messages for skipped checks.

The URL of each tool (in the skipped check messages) are now indented.

Make use of soup/is_available.sh in the Makefiles.

Synced jparse from jparse repo (https://github.com/xexyl/jparse/) with
the above changes (to do with the jparse repo).

Ran make release to test these changes in macOS.

diff --git a/soup/Makefile b/soup/Makefile
--- a/soup/Makefile
+++ b/soup/Makefile
@@ -45,6 +45,7 @@ CTAGS= ctags
 GREP= grep
 INDEPEND= independ
 INSTALL= install
+IS_AVAILABLE= ./is_available.sh
 PICKY= picky
 RANLIB= ranlib
 RM= rm
@@ -633,8 +634,8 @@ seqcexit: ${ALL_CSRC}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	${Q} if ! type -P ${SEQCEXIT} >/dev/null 2>&1; then \
-	    echo 'The ${SEQCEXIT} tool could not be found.' 1>&2; \
+	${Q} if ! ${IS_AVAILABLE} ${SEQCEXIT} >/dev/null 2>&1; then \
+	    echo 'The ${SEQCEXIT} tool could not be found or is unreliable in your system.' 1>&2; \
 	    echo 'The ${SEQCEXIT} tool is required for the $@ rule.'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo 'See the following GitHub repo for ${SEQCEXIT}:'; 1>&2; \
@@ -653,8 +654,8 @@ picky: ${ALL_SRC}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	${Q} if ! type -P ${PICKY} >/dev/null 2>&1; then \
-	    echo 'The ${PICKY} tool could not be found.' 1>&2; \
+	${Q} if ! ${IS_AVAILABLE} ${PICKY} >/dev/null 2>&1; then \
+	    echo 'The ${PICKY} tool could not be found or is unreliable in your system.' 1>&2; \
 	    echo 'The ${PICKY} tool is required for the $@ rule.' 1>&2; \
 	    echo 1>&2; \
 	    echo 'See the following GitHub repo for ${PICKY}:'; 1>&2; \
@@ -687,8 +688,8 @@ shellcheck: ${SH_FILES} .shellcheckrc
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	${Q} if ! type -P ${SHELLCHECK} >/dev/null 2>&1; then \
-	    echo 'The ${SHELLCHECK} command could not be found.' 1>&2; \
+	${Q} if ! ${IS_AVAILABLE} ${SHELLCHECK} >/dev/null 2>&1; then \
+	    echo 'The ${SHELLCHECK} command could not be found or is unreliable in your system.' 1>&2; \
 	    echo 'The ${SHELLCHECK} command is required to run the $@ rule.'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo 'See the following GitHub repo for ${SHELLCHECK}:'; 1>&2; \
@@ -715,7 +716,7 @@ check_man: ${ALL_MAN_TARGETS}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	${Q} if ! type -P ${CHECKNR} >/dev/null 2>&1; then \
+	${Q} if ! ${IS_AVAILABLE} ${CHECKNR} >/dev/null 2>&1; then \
 	    echo 'The ${CHECKNR} command could not be found.' 1>&2; \
 	    echo 'The ${CHECKNR} command is required to run the $@ rule.' 1>&2; \
 	    echo ''; 1>&2; \
@@ -751,7 +752,7 @@ tags:
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	${Q} if ! type -P ${CTAGS} >/dev/null 2>&1; then \
+	${Q} if ! ${IS_AVAILABLE} ${CTAGS} >/dev/null 2>&1; then \
 	    echo 'The ${CTAGS} command could not be found.' 1>&2; \
 	    echo 'The ${CTAGS} command is required to run the $@ rule.'; 1>&2; \
 	    echo ''; 1>&2; \
@@ -781,7 +782,7 @@ local_dir_tags: ${ALL_CSRC} ${ALL_HSRC}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	${Q} if ! type -P ${CTAGS} >/dev/null 2>&1; then \
+	${Q} if ! ${IS_AVAILABLE} ${CTAGS} >/dev/null 2>&1; then \
 	    echo 'The ${CTAGS} command could not be found.' 1>&2; \
 	    echo 'The ${CTAGS} command is required to run the $@ rule.'; 1>&2; \
 	    echo ''; 1>&2; \
@@ -912,22 +913,22 @@ uninstall:
 depend: ${ALL_CSRC}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
-	${Q} if ! type -P ${INDEPEND} >/dev/null 2>&1; then \
-	    echo '${OUR_NAME}: The ${INDEPEND} command could not be found.' 1>&2; \
+	${Q} if ! ${IS_AVAILABLE} ${INDEPEND} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${INDEPEND} command could not be found or is unreliable in your system.' 1>&2; \
 	    echo '${OUR_NAME}: The ${INDEPEND} command is required to run the $@ rule'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo 'See the following GitHub repo for ${INDEPEND}:'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo '    https://github.com/lcn2/independ'; 1>&2; \
-	elif ! type -P ${SED} >/dev/null 2>&1; then \
+	elif ! ${IS_AVAILABLE} ${SED} >/dev/null 2>&1; then \
 	    echo '${OUR_NAME}: The ${SED} command could not be found.' 1>&2; \
 	    echo '${OUR_NAME}: The ${SED} command is required to run the $@ rule'; 1>&2; \
 	    echo ''; 1>&2; \
-	elif ! type -P ${GREP} >/dev/null 2>&1; then \
+	elif ! ${IS_AVAILABLE} ${GREP} >/dev/null 2>&1; then \
 	    echo '${OUR_NAME}: The ${GREP} command could not be found.' 1>&2; \
 	    echo '${OUR_NAME}: The ${GREP} command is required to run the $@ rule'; 1>&2; \
 	    echo ''; 1>&2; \
-	elif ! type -P ${CMP} >/dev/null 2>&1; then \
+	elif ! ${IS_AVAILABLE} ${CMP} >/dev/null 2>&1; then \
 	    echo '${OUR_NAME}: The ${CMP} command could not be found.' 1>&2; \
 	    echo '${OUR_NAME}: The ${CMP} command is required to run the $@ rule'; 1>&2; \
 	    echo ''; 1>&2; \
@@ -964,7 +965,7 @@ chk_validate.o: ../dbg/dbg.h ../dyn_array/dyn_array.h ../jparse/jparse.h \
     ../jparse/jparse.tab.h ../jparse/json_parse.h ../jparse/json_sem.h \
     ../jparse/json_utf8.h ../jparse/json_util.h ../jparse/util.h \
     ../jparse/version.h chk_sem_auth.h chk_sem_info.h chk_validate.c \
-    chk_validate.h entry_time.h entry_util.h location.h
+    chk_validate.h entry_time.h entry_util.h location.h version.h
 entry_time.o: ../dbg/dbg.h ../dyn_array/dyn_array.h ../jparse/jparse.h \
     ../jparse/jparse.tab.h ../jparse/json_parse.h ../jparse/json_sem.h \
     ../jparse/json_utf8.h ../jparse/json_util.h ../jparse/util.h \
