Improve Makefiles (install, uninstall rules)
Add to Makefiles the 'PREFIX' variable to allow for installing to a
different location than the default /usr/local.

Added some uninstall rules to the Makefile in a number of subdirectories. The
external repos that are synced to this repo have not had any direct changes as
those repos first need those rules (which will be done soon). This is also why
the top level Makefile does not run 'make uninstall' in those subdirectories.
Once these are all done the top level Makefile can have a simpler uninstall
rule.

Along the lines of silencing (non-verbose) install in the install rule one
may now do the same with the uninstall (instead of 'INSTALL_V' it is 'RM_V').
This is only done to be congruent with the install rule.

Updated the MKIOCCCENTRY_REPO_VERSION to "1.5.7 2024-09-01".

diff --git a/soup/Makefile b/soup/Makefile
--- a/soup/Makefile
+++ b/soup/Makefile
@@ -115,11 +115,37 @@ else
 Q_V_OPTION="1"
 endif
 
+# installing variables
+#
+
 # INSTALL_V=				install w/o -v flag (quiet mode)
 # INSTALL_V= -v				install with -v (debug / verbose mode
 #
 #INSTALL_V=
 INSTALL_V= -v
+
+# where to install
+#
+# Default PREFIX is /usr/local so binaries would be installed in /usr/local/bin,
+# libraries in /usr/local/lib etc. If one wishes to override this, say
+# installing to /usr, they can do so like:
+#
+#	make PREFIX=/usr install
+#
+PREFIX= /usr/local
+
+# uninstalling variables
+#
+
+# RM_V=					rm w/o -v flag (quiet mode)
+# RM_V= -v				rm with -v (debug / verbose mode)
+#
+#RM_V=
+RM_V= -v
+
+# Additional controls
+#
+
 
 # MAKE_CD_Q= --no-print-directory	silence make cd messages (quiet mode)
 # MAKE_CD_Q=				silence make cd messages (quiet mode)
@@ -258,12 +284,12 @@ ALL_MAN_BUILT= ${MAN1_BUILT} ${MAN3_BUILT} ${MAN8_BUILT}
 
 # where to install
 #
-MAN1_DIR= /usr/local/share/man/man1
-MAN3_DIR= /usr/local/share/man/man3
-MAN8_DIR= /usr/local/share/man/man8
-DEST_INCLUDE= /usr/local/include
-DEST_LIB= /usr/local/lib
-DEST_DIR= /usr/local/bin
+MAN1_DIR= ${PREFIX}/share/man/man1
+MAN3_DIR= ${PREFIX}/share/man/man3
+MAN8_DIR= ${PREFIX}/share/man/man8
+DEST_INCLUDE= ${PREFIX}/include
+DEST_LIB= ${PREFIX}/lib
+DEST_DIR= ${PREFIX}/bin
 
 
 #################################
@@ -843,6 +869,29 @@ install: all install_man
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ ending"
 
+uninstall:
+	${S} echo
+	${S} echo "${OUR_NAME}: make $@ starting"
+	${S} echo
+	${RM} -r -f ${RM_V} ${DEST_LIB}/soup.a
+	${RM} -r -f ${RM_V} ${DEST_DIR}/vermod.sh
+	${RM} -r -f ${RM_V} ${DEST_DIR}/reset_tstamp.sh
+	${RM} -r -f ${RM_V} ${DEST_DIR}/all_sem_ref.sh
+	${RM} -r -f ${RM_V} ${DEST_DIR}/location
+	${RM} -r -f ${RM_V} ${DEST_DIR}/run_usage.sh
+	${RM} -r -f ${RM_V} ${MAN1_DIR}/bug_report.1
+	${RM} -r -f ${RM_V} ${MAN1_DIR}/bug_report.sh.1
+	${RM} -r -f ${RM_V} ${MAN1_DIR}/chkentry.1
+	${RM} -r -f ${RM_V} ${MAN1_DIR}/iocccsize.1
+	${RM} -r -f ${RM_V} ${MAN1_DIR}/mkiocccentry.1
+	${RM} -r -f ${RM_V} ${MAN1_DIR}/txzchk.1
+	${RM} -r -f ${RM_V} ${MAN1_DIR}/location.1
+	${RM} -r -f ${RM_V} ${MAN8_DIR}/all_sem_ref.8
+	${RM} -r -f ${RM_V} ${MAN8_DIR}/reset_tstamp.8
+	${RM} -r -f ${RM_V} ${MAN8_DIR}/run_usage.8
+	${RM} -r -f ${RM_V} ${MAN8_DIR}/vermod.8
+	${S} echo
+	${S} echo "${OUR_NAME}: make $@ ending"
 
 ###############
 # make depend #
@@ -858,6 +907,18 @@ depend: ${ALL_CSRC}
 	    echo 'See the following GitHub repo for ${INDEPEND}:'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo '    https://github.com/lcn2/independ'; 1>&2; \
+	elif ! type -P ${SED} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${SED} command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The ${SED} command is required to run the $@ rule'; 1>&2; \
+	    echo ''; 1>&2; \
+	elif ! type -P ${GREP} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${GREP} command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The ${GREP} command is required to run the $@ rule'; 1>&2; \
+	    echo ''; 1>&2; \
+	elif ! type -P ${CMP} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${CMP} command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The ${CMP} command is required to run the $@ rule'; 1>&2; \
+	    echo ''; 1>&2; \
 	else \
 	    if ! ${GREP} -q '^### DO NOT CHANGE MANUALLY BEYOND THIS LINE$$' Makefile; then \
 	        echo "${OUR_NAME}: make $@ aborting, Makefile missing: ### DO NOT CHANGE MANUALLY BEYOND THIS LINE" 1>&2; \
