Checkpoint towards a better multi-Makefile setup
Removed use of man2html.

Cleaned up .gitignore in light of the new sub-directories.

Advanced the use of c17 C standard, in the Makefile comment,
to the year 2023.

Added .git and .gitignore to .exclude to prevent these
files from being compared by diff and copied by rsync.

Added Makefile to man sub-directory.  All references
to man pages have been removed from Makefile and
and now under the control of man/Makefile.

The man/dyn_array.3 is now copied from dyn_array/dyn_array.3
and removed by make clobber.

The man/dbg.3 is now copied from dbg/dbg.3
and removed by make clobber.

Will print ERROR and path to checknr on checknr non-zero exit.
Will exit 23 on checknr non-zero exit.

The soup rule was removed from all and moved to within the just_all rule.

Changed dyn_alloc/Makefile to use the same style as dbg/Makefile.

The top level Makefile uses dyn_array/dyn_array.a instead of dyn_array/dyn_array.o.

A failure of the check_man make rule will not abort make.

Makefiles (mostly) invoke rules in other Makefile directories if
the file in that other directories does not exist or is out or date
with respect to the Makefile in that other directory.

diff --git a/dyn_array/Makefile b/dyn_array/Makefile
--- a/dyn_array/Makefile
+++ b/dyn_array/Makefile
@@ -2,17 +2,17 @@
 #
 # dyn_array - dynamic array facility
 #
-# Copyright (c) 2014,2015,2022 by Landon Curt Noll.  All Rights Reserved.
+# Copyright (c) 2022 by Landon Curt Noll.  All Rights Reserved.
 #
 # Permission to use, copy, modify, and distribute this software and
 # its documentation for any purpose and without fee is hereby granted,
 # provided that the above copyright, this permission notice and text
 # this comment, and the disclaimer below appear in all of the following:
 #
-#        supporting documentation
-#        source copies
-#        source works derived from this source
-#        binaries derived from this source or from derived source
+#       supporting documentation
+#       source copies
+#       source works derived from this source
+#       binaries derived from this source or from derived source
 #
 # LANDON CURT NOLL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
 # INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
@@ -31,32 +31,42 @@
 # utilities #
 #############
 
+# suggestion: List utility filenames, not paths.
+#	      Do not list shell builtin (echo, cd, ...) tools.
+#	      Keep the list in alphabetical order.
+#
+AR= ar
+CAT= cat
 CC= cc
+CHECKNR= checknr
+CP= cp
+CTAGS= ctags
+GREP= grep
+INSTALL= install
+RANLIB= ranlib
 RM= rm
 SHELL= bash
 
 
-#######################
-# Makefile parameters #
-#######################
+##################
+# How to compile #
+##################
 
-# linker options
+# C source standards being used
 #
-LDFLAGS=
-
 # This repo supports c11 and later.
 #
 # NOTE: The use of -std=gnu11 is because there are a few older systems
-#	in late 2021 that do not have compilers that (yet) support gnu17.
-#	While there may be even more out of date systems that do not
-#	support gnu11, we have to draw the line somewhere.
+#       in late 2021 that do not have compilers that (yet) support gnu17.
+#       While there may be even more out of date systems that do not
+#       support gnu11, we have to draw the line somewhere.
 #
-#	--------------------------------------------------
+#       --------------------------------------------------
 #
-#	^^ the line is above :-)
+#       ^^ the line is above :-)
 #
 # TODO - ###################################################################### - TODO #
-# TODO - In 2024 we will will support only c17 so C_STD will become -std=gnu17  - TODO #
+# TODO - In 2023 we will will support only c17 so C_STD will become -std=gnu17  - TODO #
 # TODO - ###################################################################### - TODO #
 #
 C_STD= -std=gnu11
@@ -64,54 +74,252 @@ C_STD= -std=gnu11
 
 # optimization and debug level
 #
-#COPT= -O3 -g3	# TODO - this will be the production release value - TODO #
-COPT= -O0 -g
+C_OPT= -O3 -g3
+#C_OPT= -O0 -g
 
 # Compiler warnings
 #
-#WARN_FLAGS= -Wall -Wextra	# TODO - this will be the production release value - TODO #
-WARN_FLAGS= -Wall -Wextra -Werror
+WARN_FLAGS= -pedantic -Wall -Wextra
+#WARN_FLAGS= -pedantic -Wall -Wextra -Werror
+
+# linker options
+#
+LDFLAGS=
 
 # how to compile
 #
-# We test by forcing warnings to be errors so you don't have to (allegedly :-) )
+# NOTE: If you use ASAN, set this environment var:
+#       ASAN_OPTIONS="detect_stack_use_after_return=1"
 #
-CFLAGS= ${C_STD} ${COPT} -pedantic ${WARN_FLAGS} ${LDFLAGS}
+CFLAGS= ${C_STD} ${C_OPT} ${WARN_FLAGS} ${LDFLAGS}
+#CFLAGS= ${C_STD} -O0 -g ${WARN_FLAGS} ${LDFLAGS} -fsanitize=address -fno-omit-frame-pointer
 
-# where and what to install
+
+###############
+# source code #
+###############
+
+# source files that are permanent (not made, nor removed)
 #
-MAN1_DIR = /usr/local/share/man/man1
-MAN8_DIR = /usr/local/share/man/man8
-MAN3_DIR = /usr/local/share/man/man3
-DESTDIR= /usr/local/bin
-TARGETS= dyn_array.o
+C_SRC= dyn_array.c dyn_test.c
+H_SRC= dyn_array.h dyn_array.h
+ALL_SRC= ${C_SRC} ${H_SRC}
 
 
-######################################
-# all - default rule - must be first #
-######################################
+######################
+# intermediate files #
+######################
 
-all: ${TARGETS}
+# NOTE: ${LIB_OBJS} are objects to put into a library and removed by make clean
+#
+LIB_OBJS= dyn_array.o
+
+# NOTE: ${OTHER_OBJS} are objects NOT put into a library and removed by make clean
+#
+OTHER_OBJS= dyn_test.o
+
+# NOTE: intermediate files to make and removed by make clean
+#
+BUILT_C_SRC=
+BUILT_H_SRC=
+ALL_BUILT_SRC= ${BUILT_C_SRC} ${BUILT_H_SRC}
+
+# all intermediate files and removed by make clean
+#
+ALL_OBJS= ${LIB_OBJS} ${OTHER_OBJS}
+
+
+#######################
+# install information #
+#######################
+
+# where to install
+#
+MAN1_DIR= /usr/local/share/man/man1
+MAN3_DIR= /usr/local/share/man/man3
+MAN8_DIR= /usr/local/share/man/man8
+DEST_INCLUDE= /usr/local/include
+DEST_LIB= /usr/local/lib
+DEST_DIR= /usr/local/bin
+
+
+#################################
+# external Makefile information #
+#################################
+
+# may be used outside of this directory
+#
+EXTERN_H= dyn_array.h
+EXTERN_O= dyn_array.o
+EXTERN_MAN= ${ALL_MAN_TARGETS}
+EXTERN_LIBA= dyn_array.a
+EXTERN_PROG= dyn_test
+
+# NOTE: ${EXTERN_CLOBBER} used outside of this directory and removed by make clobber
+#
+EXTERN_CLOBBER= ${EXTERN_O} ${EXTERN_LIBA} ${EXTERN_PROG}
+
+
+######################
+# target information #
+######################
+
+# man pages
+#
+MAN1_TARGETS=
+MAN3_TARGETS= dyn_array.3
+MAN8_TARGETS=
+ALL_MAN_TARGETS= ${MAN1_TARGETS} ${MAN3_TARGETS} ${MAN8_TARGETS}
+
+# libraries
+#
+LIBA_TARGETS= dyn_array.a
+
+# include files
+#
+H_SRC_TARGETS= dyn_array.h
+
+# what to make by all but NOT to removed by clobber (because they are not files)
+#
+ALL_OTHER_TARGETS= extern_everything
+
+# what to make by all and removed by clobber (and thus not ${ALL_OTHER_TARGETS})
+#
+TARGETS= ${LIBA_TARGETS} dyn_test
+
+
+###########################################
+# all rule - default rule - must be first #
+###########################################
+
+all: ${TARGETS} ${ALL_OTHER_TARGETS} Makefile
 	@:
 
-.PHONY: all
 
-dyn_array.o: dyn_array.c dyn_array.h Makefile
+######################################################
+# List rules that do not create themselves as .PHONY #
+######################################################
+
+.PHONY: all configure clean clobber install test \
+	extern_include extern_objs extern_liba extern_man extern_prog extern_everything
+
+
+################
+# what to make #
+################
+
+dyn_array.o: dyn_array.c dyn_array.h
 	${CC} ${CFLAGS} dyn_array.c -c
 
+dyn_array.a: ${LIB_OBJS}
+	${RM} -f $@
+	${AR} -r -u -v $@ $^
+	${RANLIB} $@
 
-###################################
-# standard Makefile utility rules #
-###################################
+dyn_test.o: dyn_test.c dyn_array.h
+	${CC} ${CFLAGS} dyn_test.c -c
+
+dyn_test: dyn_test.o ../dbg/dbg.a ../util.o dyn_array.a Makefile
+	${CC} ${CFLAGS} dyn_test.o ../dbg/dbg.a ../util.o dyn_array.a -o dyn_test
+
+
+#############################################################
+# rules that invoke rules in Makefiles in other directories #
+#############################################################
+
+../dbg/dbg.a: ../dbg/Makefile
+	${MAKE} -C ../dbg extern_liba
+
+../util.o: ../Makefile
+	${MAKE} -C .. util.o
+
+
+###########################################
+# rules for use by higher level Makefiles #
+###########################################
+
+extern_include: ${EXTERN_H}
+	@:
+
+extern_objs: ${EXTERN_O}
+	@:
+
+extern_liba: ${EXTERN_LIBA}
+	@:
+
+extern_man: ${EXTERN_MAN}
+	@:
+
+extern_prog: ${EXTERN_PROG}
+	@:
+
+extern_everything: extern_include extern_objs extern_liba extern_man extern_prog
+	@:
+
+#######################
+# internal make rules #
+#######################
+
+test: check_man dyn_test Makefile
+	@-./dyn_test; \
+	status="$$?"; \
+	if [[ $$status -ne 0 ]]; then \
+	    echo 'ERROR: dyn_test failed, error code: $$status'; \
+	else \
+	    echo "PASSED: dyn_test"; \
+	fi
+
+# inspect and verify man pages
+#
+check_man: ${ALL_MAN_TARGETS} Makefile
+	@-HAVE_CHECKNR="`type -P ${CHECKNR}`"; if [[ -z "$$HAVE_CHECKNR" ]]; then \
+	    echo 'The checknr command could not be found.' 1>&2; \
+	    echo 'The checknr command is required to run the $@ rule.' 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'The source code and install instructions for checknr are available from this GitHub repo:' 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/lcn2/checknr' 1>&2; \
+	    echo ''; 1>&2; \
+	else \
+	    echo "${CHECKNR} -c.BR.SS.BI ${ALL_MAN_TARGETS}"; \
+	    ${CHECKNR} -c.BR.SS.BI ${ALL_MAN_TARGETS}; \
+	    status="$$?"; \
+	    if [[ $$status -ne 0 ]]; then \
+		echo 'ERROR: checknr: ${CHECKNR} failed, error code: $$status'; \
+		exit 23; \
+	    fi; \
+	fi
+
+
+#######################
+# common make actions #
+#######################
 
 configure:
 	@echo nothing to $@
 
 clean:
-	@:
+	${RM} -f ${ALL_OBJS}
+	${RM} -f ${ALL_BUILT_SRC}
 
 clobber: clean
 	${RM} -f ${TARGETS}
+	${RM} -f ${EXTERN_CLOBBER}
+	${RM} -f tags
 
 install: all
-	@echo nothing to $@
+	${INSTALL} -v -d -m 0775 ${DEST_LIB}
+#none#	${INSTALL} -v -d -m 0775 ${DEST_DIR}
+#none#	${INSTALL} -v -d -m 0775 ${MAN1_DIR}
+	${INSTALL} -v -d -m 0775 ${MAN3_DIR}
+#none#	${INSTALL} -v -d -m 0775 ${MAN8_DIR}
+	${INSTALL} -v -d -m 0775 ${DEST_INCLUDE}
+#none#	${INSTALL} -v -m 0444 ${MAN1_TARGETS} ${MAN1_DIR}
+	${INSTALL} -v -m 0444 ${MAN3_TARGETS} ${MAN3_DIR}
+#none#	${INSTALL} -v -m 0444 ${MAN8_TARGETS} ${MAN8_DIR}
+	${INSTALL} -v -m 0444 ${LIBA_TARGETS} ${DEST_LIB}
+	${INSTALL} -v -m 0444 ${H_SRC_TARGETS} ${DEST_INCLUDE}
+
+tags: ${ALL_SRC} ${ALL_BUILT_SRC}
+	-${CTAGS} ${ALL_SRC} ${ALL_BUILT_SRC} 2>&1 | \
+	     ${GREP} -E -v 'Duplicate entry|Second entry ignored'
