Update picky URL + improve URLs in Makefiles
A while back the original picky website was no longer online so I made a
picky GitHub repo which is at https://github.com/xexyl/picky. The
Makefiles now refer to this URL instead of the old one and I also made
the text more consistent with some of the other rules that also refer to
a URL (though it's not entirely finished - there are still some
inconsistencies in text).

I also made _URL variables in the Makefiles for tools that we give a URL
for. This is to make it easier to refer to in the Makefile without
having to update the raw URL in every Makefile. Instead we simply update
the variable and nothing else needs to be changed.

diff --git a/dyn_array/Makefile b/dyn_array/Makefile
--- a/dyn_array/Makefile
+++ b/dyn_array/Makefile
@@ -51,6 +51,14 @@ SED= sed
 SEQCEXIT= seqcexit
 SHELL= bash
 
+######################
+# URLs for utilities #
+######################
+CHECKNR_URL = https://github.com/lcn2/checknr
+PICKY_URL= https://github.com/xexyl/picky
+SEQCEXIT_URL= https://github.com/lcn2/seqcexit
+
+
 
 ####################
 # Makefile control #
@@ -423,7 +431,7 @@ seqcexit: ${ALL_CSRC}
 	    echo ''; 1>&2; \
 	    echo 'See the following GitHub repo for seqcexit:'; 1>&2; \
 	    echo ''; 1>&2; \
-	    echo '    https://github.com/lcn2/seqcexit'; 1>&2; \
+	    echo '    ${SEQCEXIT_URL}'; 1>&2; \
 	    echo ''; 1>&2; \
 	    exit 1; \
 	else \
@@ -438,12 +446,11 @@ picky: ${ALL_SRC}
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
 	${Q} if ! type -P ${PICKY} >/dev/null 2>&1; then \
-	    echo "The picky tool could not be found." 1>&2; \
-	    echo "The picky tool is required for this rule." 1>&2; \
-	    echo "We recommend you install picky v2.6 or later" 1>&2; \
-	    echo "from this URL:" 1>&2; \
+	    echo 'The picky tool could not be found.' 1>&2; \
+	    echo 'The picky tool is required for this rule.' 1>&2; \
+	    echo 'See the following GitHub repo for picky:'; 1>&2; \
 	    echo 1>&2; \
-	    echo "http://grail.eecs.csuohio.edu/~somos/picky.html" 1>&2; \
+	    echo '    ${PICKY_URL}' 1>&2; \
 	    echo 1>&2; \
 	    exit 1; \
 	else \
@@ -477,10 +484,10 @@ check_man: ${ALL_MAN_TARGETS}
 	-${Q} HAVE_CHECKNR="`type -P ${CHECKNR}`"; if [[ -z "$$HAVE_CHECKNR" ]]; then \
 	    echo 'The checknr command could not be found.' 1>&2; \
 	    echo 'The checknr command is required to run the $@ rule.' 1>&2; \
+	    echo 'See the following GitHub repo for checknr:'; 1>&2; \
 	    echo ''; 1>&2; \
-	    echo 'The source code and install instructions for checknr are available from this GitHub repo:' 1>&2; \
 	    echo ''; 1>&2; \
-	    echo '    https://github.com/lcn2/checknr' 1>&2; \
+	    echo '    ${CHECKNR_URL}' 1>&2; \
 	    echo ''; 1>&2; \
 	else \
 	    echo "${CHECKNR} -c.BR.SS.BI ${ALL_MAN_TARGETS}"; \
diff --git a/jparse/Makefile b/jparse/Makefile
--- a/jparse/Makefile
+++ b/jparse/Makefile
@@ -41,6 +41,13 @@ SEQCEXIT= seqcexit
 SHELL= bash
 SHELLCHECK= shellcheck
 
+######################
+# URLs for utilities #
+######################
+CHECKNR_URL = https://github.com/lcn2/checknr
+PICKY_URL= https://github.com/xexyl/picky
+SEQCEXIT_URL= https://github.com/lcn2/seqcexit
+
 
 ####################
 # Makefile control #
@@ -636,7 +643,7 @@ seqcexit: ${FLEXFILES} ${BISONFILES} ${ALL_CSRC} test_jparse/Makefile
 	    echo ''; 1>&2; \
 	    echo 'See the following GitHub repo for seqcexit:'; 1>&2; \
 	    echo ''; 1>&2; \
-	    echo '    https://github.com/lcn2/seqcexit'; 1>&2; \
+	    echo '    ${SEQCEXIT_URL}'; 1>&2; \
 	    echo ''; 1>&2; \
 	    exit 1; \
 	else \
@@ -654,12 +661,11 @@ picky: ${ALL_SRC} test_jparse/Makefile
 	${S} echo
 	${M} ${MAKE} ${MAKE_CD_Q} -C test_jparse all $@
 	${Q} if ! type -P ${PICKY} >/dev/null 2>&1; then \
-	    echo "The picky tool could not be found." 1>&2; \
-	    echo "The picky tool is required for this rule." 1>&2; \
-	    echo "We recommend you install picky v2.6 or later" 1>&2; \
-	    echo "from this URL:" 1>&2; \
+	    echo 'The picky tool could not be found.' 1>&2; \
+	    echo 'The picky tool is required for this rule.' 1>&2; \
+	    echo 'See the following GitHub repo for picky:'; 1>&2; \
 	    echo 1>&2; \
-	    echo "http://grail.eecs.csuohio.edu/~somos/picky.html" 1>&2; \
+	    echo '    ${PICKY_URL}' 1>&2; \
 	    echo 1>&2; \
 	    exit 1; \
 	else \
@@ -720,9 +726,9 @@ check_man: ${ALL_MAN_TARGETS}
 	    echo 'The checknr command could not be found.' 1>&2; \
 	    echo 'The checknr command is required to run the $@ rule.' 1>&2; \
 	    echo ''; 1>&2; \
-	    echo 'The source code and install instructions for checknr are available from this GitHub repo:' 1>&2; \
+	    echo 'See the following GitHub repo for checknr:'; 1>&2; \
 	    echo ''; 1>&2; \
-	    echo '    https://github.com/lcn2/checknr' 1>&2; \
+	    echo '    ${CHECKNR_URL}' 1>&2; \
 	    echo ''; 1>&2; \
 	else \
 	    echo "${CHECKNR} -c.BR.SS.BI ${ALL_MAN_TARGETS}"; \
