sync with jparse repo clone, sync dbg and dyn_alloc
Performed `make release` to test the above under macOS.

TODO: Test under RHEL9 Linux.

diff --git a/jparse/Makefile b/jparse/Makefile
--- a/jparse/Makefile
+++ b/jparse/Makefile
@@ -100,11 +100,27 @@ else
 Q_V_OPTION="1"
 endif
 
+# installing variables
+#
+
 # INSTALL_V=				install w/o -v flag (quiet mode)
 # INSTALL_V= -v				install with -v (debug / verbose mode)
 #
 #INSTALL_V=
 INSTALL_V= -v
+
+# where to install
+#
+# Default PREFIX is /usr/local so binaries would be installed in /usr/local/bin,
+# libraries in /usr/local/lib etc. If one wishes to override this, say
+# installing to /usr, they can do so like:
+#
+#	make PREFIX=/usr install
+#
+PREFIX= /usr/local
+
+# uninstalling variables
+#
 
 # RM_V=					rm w/o -v flag (quiet mode)
 # RM_V= -v				rm with -v (debug / verbose mode)
@@ -112,7 +128,8 @@ INSTALL_V= -v
 #RM_V=
 RM_V= -v
 
-
+# Additional controls
+#
 
 # MAKE_CD_Q= --no-print-directory	silence make cd messages (quiet mode)
 # MAKE_CD_Q=				silence make cd messages (quiet mode)
@@ -165,14 +182,18 @@ WARN_FLAGS= -pedantic -Wall -Wextra -Wno-unused-but-set-variable -Wno-char-subsc
 #
 C_SPECIAL=
 
+# special linker flags
+#
+LD_SPECIAL=
+
 # linker options
 #
-LDFLAGS=
+LDFLAGS= ${LD_SPECIAL}
 
 # how to compile
+#
 CFLAGS= ${C_STD} ${C_OPT} ${WARN_FLAGS} ${C_SPECIAL} ${LDFLAGS}
 #CFLAGS= -O3 -g3 -pedantic -Wall -Werror ${C_SPECIAL}
-
 
 ###############
 # source code #
@@ -196,11 +217,11 @@ BISONFILES= jparse.y
 
 # all shell scripts
 #
-SH_FILES= jsemcgen.sh run_bison.sh run_flex.sh
+SH_FILES= jsemcgen.sh run_bison.sh run_flex.sh jparse_bug_report.sh
 
 # all man pages that NOT built and NOT removed by make clobber
 #
-MAN1_PAGES= man/man1/jparse.1 man/man1/jstrdecode.1 man/man1/jstrencode.1
+MAN1_PAGES= man/man1/jparse.1 man/man1/jstrdecode.1 man/man1/jstrencode.1 man/man1/jparse_bug_report.1
 MAN3_PAGES= man/man3/jparse.3 man/man3/json_dbg.3 man/man3/json_dbg_allowed.3 \
 	    man/man3/json_err_allowed.3 man/man3/json_warn_allowed.3 man/man3/parse_json.3 \
 	    man/man3/parse_json_file.3 man/man3/parse_json_stream.3
@@ -320,12 +341,12 @@ ALL_SRC= ${ALL_CSRC} ${ALL_HSRC} ${SH_FILES}
 
 # where to install
 #
-MAN1_DIR= /usr/local/share/man/man1
-MAN3_DIR= /usr/local/share/man/man3
-MAN8_DIR= /usr/local/share/man/man8
-DEST_INCLUDE= /usr/local/include/jparse
-DEST_LIB= /usr/local/lib
-DEST_DIR= /usr/local/bin
+MAN1_DIR= ${PREFIX}/share/man/man1
+MAN3_DIR= ${PREFIX}/share/man/man3
+MAN8_DIR= ${PREFIX}/share/man/man8
+DEST_INCLUDE= ${PREFIX}/include/jparse
+DEST_LIB= ${PREFIX}/lib
+DEST_DIR= ${PREFIX}/bin
 
 
 #################################
@@ -406,6 +427,21 @@ TARGETS= ${LIBA_TARGETS} ${PROG_TARGETS} ${ALL_MAN_BUILT}
 all: ${TARGETS} ${ALL_OTHER_TARGETS} Makefile
 	${Q} ${MAKE} ${MAKE_CD_Q} -C test_jparse all C_SPECIAL=${C_SPECIAL}
 
+bug_report: jparse_bug_report.sh
+	-${Q} ./jparse_bug_report.sh -v 1
+
+bug_report-tx: jparse_bug_report.sh
+	${S} echo "${OUR_NAME}: make $@: starting test of jparse_bug_report.sh -t -x"
+	${S} echo
+	${Q} ./jparse_bug_report.sh -t -x
+	${S} echo
+	${S} echo "${OUR_NAME}: ending test of jparse_bug_report.sh -t -x"
+
+bug_report-txl: jparse_bug_report.sh
+	${S} echo "${OUR_NAME}: make $@: starting test of jparse_bug_report.sh -t -x -l"
+	${Q} ./jparse_bug_report.sh -t -x -l
+	${S} echo "${OUR_NAME}: ending test of jparse_bug_report.sh -t -x -l"
+
 
 #################################################
 # .PHONY list of rules that do not create files #
@@ -415,7 +451,8 @@ all: ${TARGETS} ${ALL_OTHER_TARGETS} Makefile
 	extern_everything man/man1/jparse.1 man/man8/jparse_test.8 \
 	parser parser-o use_json_ref rebuild_jnum_test bison flex test \
 	tags local_dir_tags all_tags check_man legacy_clean legacy_clobber \
-	load_json_ref install_man configure clean clobber install depend
+	load_json_ref install_man configure clean clobber install depend \
+	bug_report bug_report-tx bug_report-txl
 
 
 ####################################
@@ -905,6 +942,8 @@ uninstall:
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
+	# uninstall files under test_jparse:
+	${E} ${MAKE} ${MAKE_CD_Q} -C test_jparse $@ C_SPECIAL=${C_SPECIAL}
 	${I} ${RM} -r -f ${RM_V} ${DEST_LIB}/libjparse.a
 	${I} ${RM} -r -f ${RM_V} ${DEST_INCLUDE}
 	${RM} -r -f ${RM_V} ${DEST_DIR}/jparse
@@ -915,6 +954,7 @@ uninstall:
 	${RM} -r -f ${RM_V} ${DEST_DIR}/jsemcgen.sh
 	${RM} -r -f ${RM_V} ${DEST_DIR}/run_bison.sh
 	${RM} -r -f ${RM_V} ${DEST_DIR}/run_flex.sh
+	${RM} -f -v ${RM_V} ${MAN1_DIR}/jparse_bug_report.1
 	${RM} -r -f ${RM_V} ${MAN1_DIR}/jparse.1
 	${RM} -r -f ${RM_V} ${MAN1_DIR}/jstrdecode.1
 	${RM} -r -f ${RM_V} ${MAN1_DIR}/jstrencode.1
@@ -957,6 +997,18 @@ depend: ${ALL_CSRC}
 	    echo 'See the following GitHub repo for ${INDEPEND}:'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo '    https://github.com/lcn2/independ'; 1>&2; \
+	elif ! type -P ${SED} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${SED} command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The ${SED} command is required to run the $@ rule'; 1>&2; \
+	    echo ''; 1>&2; \
+	elif ! type -P ${GREP} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${GREP} command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The ${GREP} command is required to run the $@ rule'; 1>&2; \
+	    echo ''; 1>&2; \
+	elif ! type -P ${CMP} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${CMP} command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The ${CMP} command is required to run the $@ rule'; 1>&2; \
+	    echo ''; 1>&2; \
 	else \
 	    if ! ${GREP} -q '^### DO NOT CHANGE MANUALLY BEYOND THIS LINE$$' Makefile; then \
 	        echo "${OUR_NAME}: make $@ aborting, Makefile missing: ### DO NOT CHANGE MANUALLY BEYOND THIS LINE" 1>&2; \
diff --git a/jparse/test_jparse/Makefile b/jparse/test_jparse/Makefile
--- a/jparse/test_jparse/Makefile
+++ b/jparse/test_jparse/Makefile
@@ -101,11 +101,36 @@ else
 Q_V_OPTION="1"
 endif
 
+# installing variables
+
 # INSTALL_V=				install w/o -v flag (quiet mode)
 # INSTALL_V= -v				install with -v (debug / verbose mode
 #
 #INSTALL_V=
 INSTALL_V= -v
+
+# where to install
+#
+# Default PREFIX is /usr/local so binaries would be installed in /usr/local/bin,
+# libraries in /usr/local/lib etc. If one wishes to override this, say
+# installing to /usr, they can do so like:
+#
+#	make PREFIX=/usr install
+#
+PREFIX= /usr/local
+
+# uninstalling variables
+#
+
+# RM_V=					rm w/o -v flag (quiet mode)
+# RM_V= -v				rm with -v (debug / verbose mode)
+#
+#RM_V=
+RM_V= -v
+
+
+
+
 
 # MAKE_CD_Q= --no-print-directory	silence make cd messages (quiet mode)
 # MAKE_CD_Q=				silence make cd messages (quiet mode)
@@ -158,9 +183,14 @@ WARN_FLAGS= -Wall -Wextra -Wno-char-subscripts
 #
 C_SPECIAL=
 
+
+# special linker flags
+#
+LD_SPECIAL=
+
 # linker options
 #
-LDFLAGS=
+LDFLAGS= ${LD_SPECIAL}
 
 # how to compile
 #
@@ -229,8 +259,8 @@ ALL_SRC= ${ALL_CSRC} ${ALL_HSRC} ${SH_FILES}
 # where to install
 #
 DEST_INCLUDE= /usr/local/include
-DEST_LIB= /usr/local/lib
-DEST_DIR= /usr/local/bin
+DEST_LIB= ${PREFIX}/lib
+DEST_DIR= ${PREFIX}/bin
 
 
 #################################
@@ -600,6 +630,16 @@ install: all
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ ending"
 
+# uninstall: we provide this in case someone wants to deobfuscate their system. :-)
+uninstall:
+	${S} echo
+	${S} echo "${OUR_NAME}: make $@ starting"
+	${S} echo
+	${RM} -r -f ${RM_V} ${DEST_DIR}/jnum_chk
+	${RM} -r -f ${RM_V} ${DEST_DIR}/jnum_gen
+	${RM} -r -f ${RM_V} ${DEST_DIR}/pr_jparse_test
+	${S} echo
+	${S} echo "${OUR_NAME}: make $@ ending"
 
 ###############
 # make depend #
@@ -615,6 +655,18 @@ depend: ${ALL_CSRC}
 	    echo 'See the following GitHub repo for ${INDEPEND}:'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo '    https://github.com/lcn2/independ'; 1>&2; \
+	elif ! type -P ${SED} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${SED} command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The ${SED} command is required to run the $@ rule'; 1>&2; \
+	    echo ''; 1>&2; \
+	elif ! type -P ${GREP} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${GREP} command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The ${GREP} command is required to run the $@ rule'; 1>&2; \
+	    echo ''; 1>&2; \
+	elif ! type -P ${CMP} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${CMP} command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The ${CMP} command is required to run the $@ rule'; 1>&2; \
+	    echo ''; 1>&2; \
 	else \
 	    if ! ${GREP} -q '^### DO NOT CHANGE MANUALLY BEYOND THIS LINE$$' Makefile; then \
 	        echo "${OUR_NAME}: make $@ aborting, Makefile missing: ### DO NOT CHANGE MANUALLY BEYOND THIS LINE" 1>&2; \
