Sync dbg with dbg repo
Updated [dbg repo](https://github.com/lcn2/dbg) as per
commit 5f36f1768ae805755cb576b18d196c287b5de685
and in particular the `dbg/Makefile`.

The new `dbg/Makefile` rules are not yet
used by the top level `Makefile`, nevertheless
they are backward compatible previous use.

TODO: Change `dyn_array/Makefile` to conform to
      the `dbg/Makefile` style.

TODO: Change `Makefile` to conform to
      the `dbg/Makefile` style.

TODO: Change `Makefile` to make use of extern rules
      in both `dbg/Makefile` and `dyn_array/Makefile`.

diff --git a/dbg/Makefile b/dbg/Makefile
--- a/dbg/Makefile
+++ b/dbg/Makefile
@@ -1,6 +1,6 @@
 #!/usr/bin/make
 #
-# dbg - example of how to use usage(), dbg(), warn(), err()
+# dbg - info, debug, warning, error and usage message facilities
 #
 # Copyright (c) 1989,1997,2018-2022 by Landon Curt Noll.  All Rights Reserved.
 #
@@ -31,37 +31,42 @@
 # utilities #
 #############
 
+# suggestion: List utility filenames, not paths.
+#	      Do not list shell builtin (echo, cd, ...) tools.
+#	      Keep the list in alphabetical order.
+#
+AR= ar
 CAT= cat
 CC= cc
+CHECKNR= checknr
 CP= cp
+CTAGS= ctags
 GREP= grep
+INSTALL= install
+RANLIB= ranlib
 RM= rm
 SHELL= bash
 
 
-#######################
-# Makefile parameters #
-#######################
-
-# linker options
-#
-LDFLAGS=
+##################
+# How to compile #
+##################
 
 # C source standards being used
 #
 # This repo supports c11 and later.
 #
 # NOTE: The use of -std=gnu11 is because there are a few older systems
-#	in late 2021 that do not have compilers that (yet) support gnu17.
-#	While there may be even more out of date systems that do not
-#	support gnu11, we have to draw the line somewhere.
+#       in late 2021 that do not have compilers that (yet) support gnu17.
+#       While there may be even more out of date systems that do not
+#       support gnu11, we have to draw the line somewhere.
 #
-#	--------------------------------------------------
+#       --------------------------------------------------
 #
-#	^^ the line is above :-)
+#       ^^ the line is above :-)
 #
 # TODO - ###################################################################### - TODO #
-# TODO - In 2024 we will will support only c17 so C_STD will become -std=gnu17  - TODO #
+# TODO - In 2023 we will will support only c17 so C_STD will become -std=gnu17  - TODO #
 # TODO - ###################################################################### - TODO #
 #
 C_STD= -std=gnu11
@@ -69,116 +74,192 @@ C_STD= -std=gnu11
 
 # optimization and debug level
 #
-#COPT= -O3 -g3	# TODO - this will be the production release value - TODO #
-COPT= -O0 -g
+C_OPT= -O3 -g3
+#C_OPT= -O0 -g
 
 # Compiler warnings
 #
-#WARN_FLAGS= -Wall -Wextra	# TODO - this will be the production release value - TODO #
-WARN_FLAGS= -Wall -Wextra -Werror
+WARN_FLAGS= -pedantic -Wall -Wextra
+#WARN_FLAGS= -pedantic -Wall -Wextra -Werror
 
+# linker options
+#
+LDFLAGS=
 
 # how to compile
 #
-# We test by forcing warnings to be errors so you don't have to (allegedly :-) )
-#
-CFLAGS= ${C_STD} ${COPT} -pedantic ${WARN_FLAGS} ${LDFLAGS}
-
-
 # NOTE: If you use ASAN, set this environment var:
-#	ASAN_OPTIONS="detect_stack_use_after_return=1"
+#       ASAN_OPTIONS="detect_stack_use_after_return=1"
 #
-#CFLAGS= ${C_STD} -O0 -g -pedantic ${WARN_FLAGS} ${LDFLAGS} -fsanitize=address -fno-omit-frame-pointer
+CFLAGS= ${C_STD} ${C_OPT} ${WARN_FLAGS} ${LDFLAGS}
+#CFLAGS= ${C_STD} -O0 -g ${WARN_FLAGS} ${LDFLAGS} -fsanitize=address -fno-omit-frame-pointer
 
-# NOTE: For valgrind, run with:
-#
-#	valgrind --leak-check=yes --track-origins=yes --leak-resolution=high --read-var-info=yes \
-#           --leak-check=full --show-leak-kinds=all ./mkiocccentry ...
-#
-# NOTE: Replace mkiocccentry with whichever tool you want to test and the ...
-# with the arguments and options you want.
 
-# where and what to install
+###############
+# source code #
+###############
+
+# source files that are permanent (not made, nor removed)
+#
+C_SRC= dbg.c dbg_example.c dbg_test.c
+H_SRC= dbg.h
+ALL_SRC= ${C_SRC} ${H_SRC}
+
+
+######################
+# intermediate files #
+######################
+
+# NOTE: ${LIB_OBJS} are objects to put into a library and removed by make clean
+#
+LIB_OBJS= dbg.o
+
+# NOTE: ${OTHER_OBJS} are objects NOT put into a library and removed by make clean
+#
+OTHER_OBJS= dbg_test.o dbg_example.o
+
+# NOTE: intermediate files to make and removed by make clean
+#
+BUILT_C_SRC= dbg_test.c
+BUILT_H_SRC=
+ALL_BUILT_SRC= ${BUILT_C_SRC} ${BUILT_H_SRC}
+
+# all intermediate files and removed by make clean
+#
+ALL_OBJS= ${LIB_OBJS} ${OTHER_OBJS}
+
+
+#######################
+# install information #
+#######################
+
+# where to install
 #
 MAN1_DIR= /usr/local/share/man/man1
-MAN8_DIR= /usr/local/share/man/man8
 MAN3_DIR= /usr/local/share/man/man3
-DESTDIR= /usr/local/bin
-TARGETS= dbg.o dbg_test dbg_example
-SH_TARGETS=
+MAN8_DIR= /usr/local/share/man/man8
+DEST_INCLUDE= /usr/local/include
+DEST_LIB= /usr/local/lib
+DEST_DIR= /usr/local/bin
+
+
+#################################
+# external Makefile information #
+#################################
+
+# may be used outside of this directory
+#
+EXTERN_H= dbg.h
+EXTERN_O= dbg.o
+EXTERN_MAN= ${ALL_MAN_TARGETS}
+EXTERN_LIBA= dbg.a
+
+# NOTE: ${EXTERN_CLOBBER} used outside of this directory and removed by make clobber
+#
+EXTERN_CLOBBER= ${EXTERN_O} ${EXTERN_LIBA}
+
+
+######################
+# target information #
+######################
 
 # man pages
 #
-# We explicitly define the man page targets for more than three reasons:
-#
-# (0) Currently not all targets have man pages.
-# (1) Some of the targets that have man pages are not actually in the TARGETS
-#     variable. TEST_TARGETS, for example, has utf8_test, which means
-#     utf8_test.1 would be left out.
-# (2) Even when all targets have man pages if another target is added without
-#     adding a man page make install would fail and even if make install is not
-#     that likely to be used we still don't want it to fail in the case it
-#     actually is used.
-# (3) Along the lines of (2) there are some files that will have man pages
-#     (run_bison.sh and run_flex.sh for two examples) that are not targets at
-#     all but still important parts of the repo so these would be skipped as
-#     well if we directly referred to TARGETS.
-#
-MAN1_TARGETS= 
+MAN1_TARGETS=
 MAN3_TARGETS= dbg.3
 MAN8_TARGETS=
-MAN_TARGETS= ${MAN1_TARGETS} ${MAN3_TARGETS} ${MAN8_TARGETS}
-HTML_MAN_TARGETS= $(patsubst %,%.html,$(MAN_TARGETS))
-# This is a simpler way to do:
+ALL_MAN_TARGETS= ${MAN1_TARGETS} ${MAN3_TARGETS} ${MAN8_TARGETS}
+
+# libraries
 #
-#   MAN1PAGES= $(patsubst %,%.1,$(MAN1_TARGETS))
-#   MAN3PAGES= $(patsubst %,%.3,$(MAN3_TARGETS))
-#   MAN8PAGES= $(patsubst %,%.8,$(MAN8_TARGETS))
+LIBA_TARGETS= dbg.a
+
+# include files
 #
-MAN1PAGES= $(MAN1_TARGETS:=.1)
-MAN3PAGES= $(MAN3_TARGETS:=.3)
-MAN8PAGES= $(MAN8_TARGETS:=.8)
-MANPAGES= ${MAN1PAGES} ${MAN3PAGES} ${MAN8PAGES}
+H_SRC_TARGETS= dbg.h
+
+# what to make by all but NOT to removed by clobber (because they are not files)
+#
+ALL_OTHER_TARGETS= extern_all
+
+# what to make by all and removed by clobber (and thus not ${ALL_OTHER_TARGETS})
+#
+TARGETS= ${LIBA_TARGETS} dbg_test dbg_example
 
 
-######################################
-# all - default rule - must be first #
-######################################
+###########################################
+# all rule - default rule - must be first #
+###########################################
 
-all: ${TARGETS}
+all: ${TARGETS} ${ALL_OTHER_TARGETS} Makefile
 	@:
 
-.PHONY: all test configure clean clobber install
 
-dbg.o: dbg.c dbg.h Makefile
+######################################################
+# List rules that do not create themselves as .PHONY #
+######################################################
+
+.PHONY: all configure clean clobber install test \
+	extern_include extern_objs extern_liba extern_man extern_all
+
+
+################
+# what to make #
+################
+
+dbg.o: dbg.c dbg.h
 	${CC} ${CFLAGS} dbg.c -c
 
-dbg_test.c: dbg.c Makefile
+dbg.a: ${LIB_OBJS}
+	${RM} -f $@
+	${AR} -r -u -v $@ $^
+	${RANLIB} $@
+
+dbg_test.c: dbg.c
 	${RM} -f $@
 	${CP} -v -f dbg.c $@
 
-dbg_test.o: dbg_test.c dbg.h Makefile
+dbg_test.o: dbg_test.c dbg.h
 	${CC} ${CFLAGS} -DDBG_TEST dbg_test.c -c
 
-dbg_test: dbg_test.o Makefile
-	${CC} ${CFLAGS} dbg_test.o -o $@
+dbg_test: dbg_test.o dbg.a
+	${CC} ${CFLAGS} dbg_test.o dbg.a -o $@
 
-dbg_example.o:  dbg_example.c dbg.h Makefile
+dbg_example.o:  dbg_example.c dbg.h
 	${CC} ${CFLAGS} dbg_example.c -c
 
-dbg_example: dbg_example.o dbg.o Makefile
-	${CC} ${CFLAGS} dbg_example.o dbg.o -o $@
+dbg_example: dbg_example.o dbg.a
+	${CC} ${CFLAGS} dbg_example.o dbg.a -o $@
 
 
-###################################################################
-# repo tools - rules for those who maintain the mkiocccentry repo #
-###################################################################
+###########################################
+# rules for use by higher level Makefiles #
+###########################################
 
-test: dbg_test Makefile
+extern_include: ${EXTERN_H}
+	@:
+
+extern_objs: ${EXTERN_O}
+	@:
+
+extern_liba: ${EXTERN_LIBA}
+	@:
+
+extern_man: ${EXTERN_MAN}
+	@:
+
+extern_all: extern_include extern_objs extern_liba extern_man
+	@:
+
+#######################
+# internal make rules #
+#######################
+
+test: dbg_test checknr Makefile
 	${RM} -f dbg_test.out
 	@echo "RUNNING: dbg_test"
 	@echo "./dbg_test -e 2 foo bar baz >dbg_test.out 2>&1"
-	@-./dbg_test -v 1 -e 2 foo bar baz > dbg_test.out 2>&1; \
+	@-./dbg_test -v 1 -e 2 foo bar baz >dbg_test.out 2>&1; \
 	  status="$$?"; \
 	  if [[ $$status -ne 5 ]]; then \
 	    echo "exit status of dbg_test: $$status != 5"; \
@@ -197,21 +278,50 @@ test: dbg_test Makefile
 	      fi; \
 	  fi
 
+# inspect and verify man pages
+#
+checknr: ${ALL_MAN_TARGETS} Makefile
+	@HAVE_CHECKNR="`type -P ${CHECKNR}`"; if [[ -z "$$HAVE_CHECKNR" ]]; then \
+	    echo 'The checknr command could not be found.' 1>&2; \
+	    echo 'The checknr command is required to run this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${CHECKNR} -c.BR.SS.BI ${ALL_MAN_TARGETS}"; \
+	    ${CHECKNR} -c.BR.SS.BI ${ALL_MAN_TARGETS}; \
+	fi
 
-###################################
-# standard Makefile utility rules #
-###################################
+
+#######################
+# common make actions #
+#######################
 
 configure:
 	@echo nothing to $@
 
 clean:
-	${RM} -f dbg.o dbg_example.o
-	${RM} -f dbg.out
+	${RM} -f ${ALL_OBJS}
+	${RM} -f ${ALL_BUILT_SRC}
+	${RM} -f dbg_test.out
 
 clobber: clean
 	${RM} -f ${TARGETS}
-	${RM} -f dbg_test.c dbg_test.o dbg_test.out
+	${RM} -f ${EXTERN_CLOBBER}
+	${RM} -f tags
 
 install: all
-	@echo nothing to $@
+	${INSTALL} -v -d -m 0775 ${DEST_LIB}
+	${INSTALL} -v -d -m 0775 ${DEST_DIR}
+#none#	${INSTALL} -v -d -m 0775 ${MAN1_DIR}
+	${INSTALL} -v -d -m 0775 ${MAN3_DIR}
+#none#	${INSTALL} -v -d -m 0775 ${MAN8_DIR}
+	${INSTALL} -v -d -m 0775 ${DEST_INCLUDE}
+#none#	${INSTALL} -v -S -m 0444 ${MAN1_TARGETS} ${MAN1_DIR}
+	${INSTALL} -v -S -m 0444 ${MAN3_TARGETS} ${MAN3_DIR}
+#none#	${INSTALL} -v -S -m 0444 ${MAN8_TARGETS} ${MAN8_DIR}
+	${INSTALL} -v -S -m 0444 ${LIBA_TARGETS} ${DEST_LIB}
+	${INSTALL} -v -S -m 0444 ${H_SRC_TARGETS} ${DEST_INCLUDE}
+
+tags: ${ALL_SRC} ${ALL_BUILT_SRC}
+	-${CTAGS} ${ALL_SRC} ${ALL_BUILT_SRC} 2>&1 | \
+	     ${GREP} -E -v 'Duplicate entry|Second entry ignored'
