reduce make test verbosity due to the Makefiles
The Makefile verbosity of `make test` has been greatly reduced.

Changed `make test` to be silent by default.  To restore
the previous "more test" move, try:

```sh
make test Q= V=@
```
To further reduce the `make test` verbosity, the test rule
no longer depends on all.  In some cases the test rule tests if
the critical tool is executable.  If it is not, it tries to make it
after which if the tool is still not executable, exits with an
error message.  This is NOT done for all Makefiles, nor for
all things made by make all.

The idea of `make test` is to test the current condition.
The above makes are there to be slightly helpful AND
print nothing if the critical tool already exists.

To proper test the entire tree:

```sh
make clobber all test
```

diff --git a/dbg/Makefile b/dbg/Makefile
--- a/dbg/Makefile
+++ b/dbg/Makefile
@@ -401,33 +401,42 @@ man/man3/printf_usage.3:
 # repo tools - rules for those who maintain the this repo #
 ###########################################################
 
-test: dbg_test check_man
-	@echo
-	@echo "${OUR_NAME}: make $@ starting"
-	@echo
-	${RM} -f dbg_test.out
-	@echo "RUNNING: dbg_test"
-	@echo "./dbg_test -e 2 foo bar baz >dbg_test.out 2>&1"
-	@-./dbg_test -v 1 -e 2 foo bar baz >dbg_test.out 2>&1; \
+test:
+	${V} echo
+	${V} echo "${OUR_NAME}: make $@ starting"
+	${V} echo
+	${Q} ${RM} -f dbg_test.out
+	${V} echo "RUNNING: dbg_test"
+	${V} echo "./dbg_test -e 2 foo bar baz >dbg_test.out 2>&1"
+	${Q} if [[ ! -x ./dbg_test ]]; then \
+	    echo "${OUR_NAME}: executable not found: ./dbg_test" 1>&2; \
+	    echo "${OUR_NAME}: trying to make dbg_test" 1>&2; \
+	    ${MAKE} dbg_test; \
+	fi
+	${Q} if [[ ! -x ./dbg_test ]]; then \
+	    echo "${OUR_NAME}: ERROR: unable to create excutable: ./dbg_test" 1>&2; \
+	    exit 20; \
+	fi
+	-${Q} ./dbg_test -v 1 -e 2 foo bar baz >dbg_test.out 2>&1; \
 	  EXIT_CODE="$$?"; \
 	  if [[ $$EXIT_CODE -ne 5 ]]; then \
-	    echo "exit status of dbg_test: $$EXIT_CODE != 5"; \
+	    echo "${OUR_NAME}: exit status of dbg_test: $$EXIT_CODE != 5"; \
 	    exit 21; \
 	  else \
 	      ${GREP} -q '^ERROR\[5\]: main: simulated error, foo: foo bar: bar: errno\[2\]: No such file or directory$$' dbg_test.out; \
 	      EXIT_CODE="$$?"; \
 	      if [[ $$EXIT_CODE -ne 0 ]]; then \
-		echo "ERROR: did not find the correct dbg_test error message" 1>&2; \
-		echo "ERROR: beginning dbg_test.out contents" 1>&2; \
+		echo "${OUR_NAME}: ERROR: did not find the correct dbg_test error message" 1>&2; \
+		echo "${OUR_NAME}: ERROR: beginning dbg_test.out contents" 1>&2; \
 		${CAT} dbg_test.out 1>&2; \
-		echo "ERROR: dbg_test.out contents complete" 1>&2; \
+		echo "${OUR_NAME}: ERROR: dbg_test.out contents complete" 1>&2; \
 		exit 22; \
 	      else \
-		echo "PASSED: dbg_test"; \
+		echo "${OUR_NAME}: PASSED: dbg_test"; \
 	      fi; \
 	  fi
-	@echo
-	@echo "${OUR_NAME}: make $@ complete"
+	${V} echo
+	${V} echo "${OUR_NAME}: make $@ complete"
 
 # sequence exit codes
 #
diff --git a/dyn_array/Makefile b/dyn_array/Makefile
--- a/dyn_array/Makefile
+++ b/dyn_array/Makefile
@@ -373,19 +373,28 @@ man/man3/dyn_array.3:
 # repo tools - rules for those who maintain the this repo #
 ###########################################################
 
-test: check_man dyn_test
-	@echo
-	@echo "${OUR_NAME}: make $@ starting"
-	@echo
-	@-./dyn_test; \
+test:
+	${V} echo
+	${V} echo "${OUR_NAME}: make $@ starting"
+	${V} echo
+	${Q} if [[ ! -x ./dyn_test ]]; then \
+	    echo "${OUR_NAME}: executable not found: ./dyn_test" 1>&2; \
+	    echo "${OUR_NAME}: trying to make dyn_test" 1>&2; \
+	    ${MAKE} dyn_test; \
+	fi
+	${Q} if [[ ! -x ./dyn_test ]]; then \
+	    echo "${OUR_NAME}: ERROR: unable to create excutable: ./dyn_test" 1>&2; \
+	    exit 20; \
+	fi
+	-${Q} ./dyn_test; \
 	EXIT_CODE="$$?"; \
 	if [[ $$EXIT_CODE -ne 0 ]]; then \
-	    echo 'ERROR: dyn_test failed, error code: $$EXIT_CODE'; \
+	    echo '${OUR_NAME}: ERROR: dyn_test failed, error code: $$EXIT_CODE'; \
 	else \
-	    echo "PASSED: dyn_test"; \
+	    echo ${OUR_NAME}: "PASSED: dyn_test"; \
 	fi
-	@echo
-	@echo "${OUR_NAME}: make $@ complete"
+	${V} echo
+	${V} echo "${OUR_NAME}: make $@ complete"
 
 # sequence exit codes
 #
diff --git a/jparse/Makefile b/jparse/Makefile
--- a/jparse/Makefile
+++ b/jparse/Makefile
@@ -604,13 +604,22 @@ bison: jparse.tab.c jparse.tab.h
 flex: jparse.c jparse.lex.h
 	@:
 
-test: check_man test_jparse/Makefile
-	@echo
-	@echo "${OUR_NAME}: make $@ starting"
-	@echo
-	@${MAKE} ${MAKE_CD_Q} -C test_jparse all test
-	@echo
-	@echo "${OUR_NAME}: make $@ complete"
+test: test_jparse/Makefile
+	${V} echo
+	${V} echo "${OUR_NAME}: make $@ starting"
+	${V} echo
+	${Q} if [[ ! -x ./jparse ]]; then \
+	    echo "${OUR_NAME}: executable not found: ./jparse" 1>&2; \
+	    echo "${OUR_NAME}: trying to make jparse" 1>&2; \
+	    ${MAKE} jparse; \
+	fi
+	${Q} if [[ ! -x ./jparse ]]; then \
+	    echo "${OUR_NAME}: ERROR: unable to create excutable: ./jparse" 1>&2; \
+	    exit 20; \
+	fi
+	${Q} ${MAKE} ${MAKE_CD_Q} -C test_jparse all test
+	${V} echo
+	${V} echo "${OUR_NAME}: make $@ complete"
 
 # rule used by prep.sh and make clean
 #
