checkpoint to improve Makefiles
Ignore files under `man/` that are built via the `.gitignore` file.

NOTE: When `man/` is changed to have man1, man3 and man8 sub-directories,
      the `.gitignore` file will need to be modified.

Updated utility lists for all Makefiles.  Made sure that all utilities
used somewhere in the Makefile were set as make variables in the
utility list section, which the exception of `SHELL` which has
a special Makefile meaning (the shell used to execute actions).

Changed `sleep` command to `${SLEEP}` and added `SLEEP` as a
Makefile variable in the utility section.

Sorted all variable names in the utility section of all Makefiles.

Make Makefile variable names consistent Makefiles.  For example,
in some cases `COPT` Makefile variable was changed to `C_OPT`.

Added `SH_FILES` as a Makefile variable to all Makefiles.

When a Makefile runs make in another directory, the other
directory's Makefile is listed as a dependency.

In some cases where a Makefile rule lists Makefile as a
dependency, the Makefile dependency was removed.

The parser Makefile rule at the top level Makefile no longer
depends on files under `jparse/` except for the `jparse/Makefile`.
Instead, the parser Makefile rule at the top level Makefile
will rely on the parser rule in `jparse/Makefile` to do that.

The use_ref Makefile rule at the top level Makefile no longer
depends on files under `jparse/` except for the `jparse/Makefile`.
Instead, the use_ref Makefile rule at the top level Makefile
will rely on the use_ref rule in `jparse/Makefile` to do that.

All Makefiles have seqcexit, picky, shellcheck, check_man, and
tags rules.  For those Makefiles where the given rule does not
apply, a stub action (`@:`) is performed.

The top level Makefile recursively calls seqcexit, picky, shellcheck,
check_man, and tags rules in lower level Makefiles.

The jparse Makefile recursively calls seqcexit, picky, shellcheck,
check_man, and tags rules in jparse/test_jparse Makefile.

For Makefiles with a tags rule, the clobber rule now removes tags.

While this is a cosmetic change only, all `rm -f` actions that
were empty have been eliminated in all Makefiles.

The `ALL_SRC` Makefile variable now includes `SH_FILES`.

The prep_clobber Makefile rule depends on prep_clean.
The legacy_clobber Makefile rule depends on legacy_clean.

Added a .shellcheck file to all directories that have shell scripts.

diff --git a/dbg/Makefile b/dbg/Makefile
--- a/dbg/Makefile
+++ b/dbg/Makefile
@@ -44,9 +44,11 @@ CP= cp
 CTAGS= ctags
 GREP= grep
 INSTALL= install
+PICKY= picky
 RANLIB= ranlib
 RM= rm
 SED= sed
+SEQCEXIT= seqcexit
 SHELL= bash
 
 
@@ -111,6 +113,10 @@ H_SRC= dbg.h
 LESS_PICKY_CSRC=
 LESS_PICKY_HSRC=
 
+# all shell scripts
+#
+SH_FILES=
+
 
 ######################
 # intermediate files #
@@ -138,7 +144,7 @@ ALL_OBJS= ${LIB_OBJS} ${OTHER_OBJS}
 #
 ALL_CSRC= ${C_SRC} ${LESS_PICKY_CSRC} ${BUILT_C_SRC}
 ALL_HSRC= ${H_SRC} ${LESS_PICKY_HSRC} ${BUILT_H_SRC}
-ALL_SRC= ${ALL_CSRC} ${ALL_HSRC}
+ALL_SRC= ${ALL_CSRC} ${ALL_HSRC} ${SH_FILES}
 
 
 #######################
@@ -343,6 +349,44 @@ test: dbg_test check_man Makefile
 	      fi; \
 	  fi
 
+# sequence exit codes
+#
+seqcexit: ${ALL_CSRC}
+	@HAVE_SEQCEXIT="`type -P ${SEQCEXIT}`"; if [[ -z "$$HAVE_SEQCEXIT" ]]; then \
+	    echo 'The seqcexit tool could not be found.' 1>&2; \
+	    echo 'The seqcexit tool is required for this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for seqcexit:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/lcn2/seqcexit'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}"; \
+	    ${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}; \
+	fi
+
+picky: ${ALL_SRC}
+	@if ! type -P ${PICKY} >/dev/null 2>&1; then \
+	    echo "The picky tool could not be found." 1>&2; \
+	    echo "The picky tool is required for this rule." 1>&2; \
+	    echo "We recommend you install picky v2.6 or later" 1>&2; \
+	    echo "from this URL:" 1>&2; \
+	    echo 1>&2; \
+	    echo "http://grail.eecs.csuohio.edu/~somos/picky.html" 1>&2; \
+	    echo 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}"; \
+	    ${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}; \
+	    EXIT_CODE="$$?"; if [[ $$EXIT_CODE -ne 0 ]]; then echo "picky: ERROR: $$EXIT_CODE" 1>&2; exit 1; fi; \
+	fi
+
+# inspect and verify shell scripts
+#
+shellcheck:
+	@:
+
 # inspect and verify man pages
 #
 check_man: ${ALL_MAN_TARGETS} Makefile
@@ -364,16 +408,22 @@ check_man: ${ALL_MAN_TARGETS} Makefile
 	    fi; \
 	fi
 
+# vi/vim tags
+#
+tags: ${ALL_CSRC} ${ALL_HSRC}
+	-${CTAGS} ${ALL_CSRC} ${ALL_HSRC} 2>&1 | \
+	     ${GREP} -E -v 'Duplicate entry|Second entry ignored'
+
 prep_clean: legacy_clean
 	@:
 
-prep_clobber: legacy_clobber
-	@:
+prep_clobber: prep_clean legacy_clobber
+	${RM} -f dbg_test
 
 legacy_clean:
 	@:
 
-legacy_clobber:
+legacy_clobber: legacy_clean
 	@:
 
 
@@ -385,8 +435,7 @@ configure:
 	@echo nothing to $@
 
 clean:
-	${RM} -f ${ALL_OBJS}
-	${RM} -f ${ALL_BUILT_SRC}
+	${RM} -f ${ALL_OBJS} ${ALL_BUILT_SRC}
 	${RM} -f dbg_test.out
 
 clobber: clean
@@ -406,10 +455,6 @@ install: all
 #none#	${INSTALL} -v -m 0444 ${MAN8_TARGETS} ${MAN8_DIR}
 	${INSTALL} -v -m 0444 ${LIBA_TARGETS} ${DEST_LIB}
 	${INSTALL} -v -m 0444 ${H_SRC_TARGETS} ${DEST_INCLUDE}
-
-tags: ${ALL_CSRC} ${ALL_BUILT_SRC}
-	-${CTAGS} ${ALL_CSRC} ${ALL_BUILT_SRC} 2>&1 | \
-	     ${GREP} -E -v 'Duplicate entry|Second entry ignored'
 
 ###############
 # make depend #
diff --git a/dyn_array/Makefile b/dyn_array/Makefile
--- a/dyn_array/Makefile
+++ b/dyn_array/Makefile
@@ -36,17 +36,18 @@
 #	      Keep the list in alphabetical order.
 #
 AR= ar
-CAT= cat
 CC= cc
 CHECKNR= checknr
 CMP= cmp
-CP= cp
 CTAGS= ctags
 GREP= grep
 INSTALL= install
+MAKE= make
+PICKY= picky
 RANLIB= ranlib
 RM= rm
 SED= sed
+SEQCEXIT= seqcexit
 SHELL= bash
 
 
@@ -111,6 +112,10 @@ H_SRC= dyn_array.h dyn_array.h
 LESS_PICKY_CSRC=
 LESS_PICKY_HSRC=
 
+# all shell scripts
+#
+SH_FILES=
+
 
 ######################
 # intermediate files #
@@ -138,7 +143,7 @@ ALL_OBJS= ${LIB_OBJS} ${OTHER_OBJS}
 #
 ALL_CSRC= ${C_SRC} ${LESS_PICKY_CSRC} ${BUILT_C_SRC}
 ALL_HSRC= ${H_SRC} ${LESS_PICKY_HSRC} ${BUILT_H_SRC}
-ALL_SRC= ${ALL_CSRC} ${ALL_HSRC}
+ALL_SRC= ${ALL_CSRC} ${ALL_HSRC} ${SH_FILES}
 
 
 #######################
@@ -301,6 +306,44 @@ test: check_man dyn_test Makefile
 	    echo "PASSED: dyn_test"; \
 	fi
 
+# sequence exit codes
+#
+seqcexit: ${ALL_CSRC}
+	@HAVE_SEQCEXIT="`type -P ${SEQCEXIT}`"; if [[ -z "$$HAVE_SEQCEXIT" ]]; then \
+	    echo 'The seqcexit tool could not be found.' 1>&2; \
+	    echo 'The seqcexit tool is required for this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for seqcexit:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/lcn2/seqcexit'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}"; \
+	    ${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}; \
+	fi
+
+picky: ${ALL_SRC}
+	@if ! type -P ${PICKY} >/dev/null 2>&1; then \
+	    echo "The picky tool could not be found." 1>&2; \
+	    echo "The picky tool is required for this rule." 1>&2; \
+	    echo "We recommend you install picky v2.6 or later" 1>&2; \
+	    echo "from this URL:" 1>&2; \
+	    echo 1>&2; \
+	    echo "http://grail.eecs.csuohio.edu/~somos/picky.html" 1>&2; \
+	    echo 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}"; \
+	    ${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}; EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[1]: $$EXIT_CODE" 1>&2; exit 1; fi; \
+	fi
+
+# inspect and verify shell scripts
+#
+shellcheck:
+	@:
+
 # inspect and verify man pages
 #
 check_man: ${ALL_MAN_TARGETS} Makefile
@@ -322,20 +365,22 @@ check_man: ${ALL_MAN_TARGETS} Makefile
 	    fi; \
 	fi
 
-tags: ${ALL_SRC}
-	-${CTAGS} ${ALL_SRC} 2>&1 | \
+# vi/vim tags
+#
+tags: ${ALL_CSRC} ${ALL_HSRC}
+	-${CTAGS} ${ALL_CSRC} ${ALL_HSRC} 2>&1 | \
 	     ${GREP} -E -v 'Duplicate entry|Second entry ignored'
 
 prep_clean: legacy_clean
 	@:
 
-prep_clobber: legacy_clobber
-	@:
+prep_clobber: prep_clean legacy_clobber
+	${RM} -f dyn_test
 
 legacy_clean:
 	@:
 
-legacy_clobber:
+legacy_clobber: legacy_clean
 	@:
 
 
@@ -347,8 +392,7 @@ configure:
 	@echo nothing to $@
 
 clean:
-	${RM} -f ${ALL_OBJS}
-	${RM} -f ${ALL_BUILT_SRC}
+	${RM} -f ${ALL_OBJS} ${ALL_BUILT_SRC}
 
 clobber: clean
 	${RM} -f ${TARGETS}
diff --git a/jparse/Makefile b/jparse/Makefile
--- a/jparse/Makefile
+++ b/jparse/Makefile
@@ -23,40 +23,22 @@
 #	      Do not list shell builtin (echo, cd, ...) tools.
 #	      Keep the list in alphabetical order.
 #
-AWK= awk
-BASENAME= basename
-CAT= cat
+AR= ar
 CC= cc
 CHECKNR= checknr
 CMP= cmp
 CP= cp
 CTAGS= ctags
-CUT= cut
-DIFF= diff
-FMT= fmt
-GIT= git
 GREP= grep
-HEAD= head
 INSTALL= install
 MAKE= make
-MAN2HTML= man2html
-MAN= man
-MKTEMP= mktemp
-MV= mv
 PICKY= picky
 RANLIB= ranlib
 RM= rm
-RPL= rpl
-RSYNC= rsync
 SED= sed
 SEQCEXIT= seqcexit
 SHELL= bash
 SHELLCHECK= shellcheck
-SLEEP= sleep
-TEE= tee
-TOUCH= touch
-TR= tr
-TRUE= true
 
 
 ##################
@@ -113,16 +95,24 @@ CFLAGS= ${C_STD} ${C_OPT} ${WARN_FLAGS} ${LDFLAGS}
 # source files that are permanent (not made, nor removed)
 #
 C_SRC= jparse_main.c json_parse.c json_sem.c json_util.c jnum_gen.c jnum_header.c \
-       jsemtblgen.c jstrdecode.c jstrencode.c util.c \
-       jparse.ref.c jparse.tab.ref.c
+       jsemtblgen.c jstrdecode.c jstrencode.c util.c
 H_SRC= jparse.h jnum_gen.h jparse_main.h jsemtblgen.h json_parse.h json_sem.h json_util.h \
        jstrdecode.h jstrencode.h sorry.tm.ca.h util.h verge.h \
-       jparse.lex.ref.h jparse.tab.ref.h
+       jparse.tab.ref.h
 
 # source files that do not conform to strict picky standards
 #
-LESS_PICKY_CSRC=
-LESS_PICKY_HSRC=
+LESS_PICKY_CSRC= jparse.ref.c jparse.tab.ref.c
+LESS_PICKY_HSRC= jparse.lex.ref.h
+
+# bison and flex
+#
+FLEXFILES= jparse.l
+BISONFILES= jparse.y
+
+# all shell scripts
+#
+SH_FILES= jsemcgen.sh run_bison.sh run_flex.sh
 
 
 ######################
@@ -149,7 +139,7 @@ ALL_OBJS= ${LIB_OBJS} ${OTHER_OBJS}
 
 # rule used by prep.sh and make clean via make clean_generated_obj
 #
-GENERATED_OBJ= jparse.o jparse.tab.o jparse.tab.o
+BUILT_OBJS= jparse.o jparse.tab.o jparse.tab.o
 
 # RUN_O_FLAG - determine if the bison and flex backup files should be used
 #
@@ -232,7 +222,7 @@ FLEX_FLAGS= -8
 #
 ALL_CSRC= ${C_SRC} ${LESS_PICKY_CSRC} ${BUILT_C_SRC}
 ALL_HSRC= ${H_SRC} ${LESS_PICKY_HSRC} ${BUILT_H_SRC}
-ALL_SRC= ${ALL_CSRC} ${ALL_HSRC}
+ALL_SRC= ${ALL_CSRC} ${ALL_HSRC} ${SH_FILES}
 
 
 #######################
@@ -525,21 +515,77 @@ bison: jparse.tab.c jparse.tab.h
 flex: jparse.c jparse.lex.h
 	@:
 
-test: check_man Makefile
+test: check_man test_jparse/Makefile
 	@${MAKE} -C test_jparse all test
 
 # rule used by prep.sh and make clean
 #
 clean_generated_obj:
-	${RM} -f ${GENERATED_OBJ}
+	${RM} -f ${BUILT_OBJS}
 
-tags: ${ALL_SRC} ${ALL_BUILT_SRC}
-	-${CTAGS} ${ALL_SRC} ${ALL_BUILT_SRC} 2>&1 | \
-	     ${GREP} -E -v 'Duplicate entry|Second entry ignored'
+# sequence exit codes
+#
+seqcexit: ${FLEXFILES} ${BISONFILES} ${ALL_CSRC} test_jparse/Makefile
+	@HAVE_SEQCEXIT="`type -P ${SEQCEXIT}`"; if [[ -z "$$HAVE_SEQCEXIT" ]]; then \
+	    echo 'The seqcexit tool could not be found.' 1>&2; \
+	    echo 'The seqcexit tool is required for this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for seqcexit:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/lcn2/seqcexit'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${SEQCEXIT} -c -D werr_sem_val -D werrp_sem_val -- ${FLEXFILES} ${BISONFILES}"; \
+	    ${SEQCEXIT} -c -D werr_sem_val -D werrp_sem_val -- ${FLEXFILES} ${BISONFILES}; \
+	    echo "${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}"; \
+	    ${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}; \
+	fi
+	@${MAKE} -C test_jparse all $@
+
+picky: ${ALL_SRC} test_jparse/Makefile
+	@if ! type -P ${PICKY} >/dev/null 2>&1; then \
+	    echo "The picky tool could not be found." 1>&2; \
+	    echo "The picky tool is required for this rule." 1>&2; \
+	    echo "We recommend you install picky v2.6 or later" 1>&2; \
+	    echo "from this URL:" 1>&2; \
+	    echo 1>&2; \
+	    echo "http://grail.eecs.csuohio.edu/~somos/picky.html" 1>&2; \
+	    echo 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}"; \
+	    ${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}; EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[1]: $$EXIT_CODE" 1>&2; exit 1; fi; \
+	    echo "${PICKY} -w -u -s -t8 -v -e -8 -- ${FLEXFILES} ${BISONFILES}"; \
+	    ${PICKY} -w -u -s -t8 -v -e -8 -- ${FLEXFILES} ${BISONFILES}; EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[2]: $$EXIT_CODE" 1>&2; exit 2; fi; \
+	fi
+	@${MAKE} -C test_jparse all $@
+
+# inspect and verify shell scripts
+#
+shellcheck: ${SH_FILES} .shellcheckrc test_jparse/Makefile
+	@HAVE_SHELLCHECK="`type -P ${SHELLCHECK}`"; if [[ -z "$$HAVE_SHELLCHECK" ]]; then \
+	    echo 'The shellcheck command could not be found.' 1>&2; \
+	    echo 'The shellcheck command is required to run this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for shellcheck:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/koalaman/shellcheck.net'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'Or use the package manager in your OS to install it.' 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${SHELLCHECK} -f gcc -- ${SH_FILES}"; \
+	    ${SHELLCHECK} -f gcc -- ${SH_FILES}; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[1]: $$EXIT_CODE" 1>&2; exit 1; fi; \
+	fi
+	@${MAKE} -C test_jparse all $@
 
 # inspect and verify man pages
 #
-check_man: ${ALL_MAN_TARGETS} Makefile
+check_man: ${ALL_MAN_TARGETS} test_jparse/Makefile
 	@-HAVE_CHECKNR="`type -P ${CHECKNR}`"; if [[ -z "$$HAVE_CHECKNR" ]]; then \
 	    echo 'The checknr command could not be found.' 1>&2; \
 	    echo 'The checknr command is required to run the $@ rule.' 1>&2; \
@@ -557,19 +603,27 @@ check_man: ${ALL_MAN_TARGETS} Makefile
 		exit 23; \
 	    fi; \
 	fi
+	@${MAKE} -C test_jparse all $@
 
-prep_clean: legacy_clean
+# vi/vim tags
+#
+tags: ${ALL_CSRC} ${ALL_HSRC} test_jparse/Makefile
+	-${CTAGS} ${ALL_CSRC} ${ALL_HSRC} 2>&1 | \
+	     ${GREP} -E -v 'Duplicate entry|Second entry ignored'
+	@${MAKE} -C test_jparse all $@
+
+prep_clean: legacy_clean test_jparse/Makefile
 	${MAKE} -C test_jparse $@
 
-prep_clobber: legacy_clobber
+prep_clobber: prep_clean legacy_clobber
 	${RM} -f jnum_gen
 	${RM} -rf jnum_gen.dSYM
 	${MAKE} -C test_jparse $@
 
-legacy_clean:
+legacy_clean: test_jparse/Makefile
 	${MAKE} -C test_jparse $@
 
-legacy_clobber:
+legacy_clobber: legacy_clean test_jparse/Makefile
 	${RM} -f jstr_test.out jstr_test2.out
 	${MAKE} -C test_jparse $@
 
@@ -582,14 +636,15 @@ configure:
 	@echo nothing to $@
 
 clean:
-	${RM} -f ${LIB_OBJS}
+	${RM} -f ${ALL_OBJS} ${ALL_BUILT_SRC}
 
 clobber: clean
 	${RM} -f ${TARGETS}
 	${RM} -f jparse.output
 	${RM} -f jsemcgen.out.*
+	${RM} -f tags
 
-install: all
+install: all test_jparse/Makefile
 	${INSTALL} -v -d -m 0775 ${DEST_LIB}
 #none#	${INSTALL} -v -d -m 0775 ${DEST_DIR}
 	${INSTALL} -v -d -m 0775 ${MAN1_DIR}
@@ -601,6 +656,7 @@ install: all
 	${INSTALL} -v -m 0444 ${MAN8_TARGETS} ${MAN8_DIR}
 	${INSTALL} -v -m 0444 ${LIBA_TARGETS} ${DEST_LIB}
 	${INSTALL} -v -m 0444 ${H_SRC_TARGETS} ${DEST_INCLUDE}
+	${MAKE} -C test_jparse $@
 
 
 ###############
diff --git a/jparse/test_jparse/Makefile b/jparse/test_jparse/Makefile
--- a/jparse/test_jparse/Makefile
+++ b/jparse/test_jparse/Makefile
@@ -3,17 +3,17 @@
 # test_jparse - mkiocccentry jparse test tools
 #
 # "Because specs w/o version numbers are forced to commit to their original design flaws." :-)
-# 
+#
 # This JSON parser was co-developed by:
-# 
+#
 #	@xexyl
 # 	https://xexyl.net		Cody Boone Ferguson
 # 	https://ioccc.xexyl.net
 # and:
 # 	chongo (Landon Curt Noll, http://www.isthe.com/chongo/index.html) /\oo/\
-# 
+#
 # "Because sometimes even the IOCCC Judges need some help." :-)
-# 
+#
 # "Share and Enjoy!"
 #	--  Sirius Cybernetics Corporation Complaints Division, JSON spec department. :-)
 ####
@@ -23,37 +23,21 @@
 # utilities #
 #############
 
-AWK= awk
-BASENAME= basename
-CAT= cat
-CMP= cmp
-CUT= cut
+# suggestion: List utility filenames, not paths.
+#	      Do not list shell builtin (echo, cd, ...) tools.
+#	      Keep the list in alphabetical order.
+#
 CC= cc
-CP= cp
+CMP= cmp
 CTAGS= ctags
-DIFF= diff
-FMT= fmt
-GIT= git
 GREP= grep
-HEAD= head
-INSTALL= install
 MAKE= make
-MAN= man
-MAN2HTML= man2html
-MKTEMP= mktemp
-MV= mv
 PICKY= picky
 RM= rm
-RPL= rpl
-RSYNC= rsync
 SED= sed
 SEQCEXIT= seqcexit
 SHELL= bash
 SHELLCHECK= shellcheck
-CHECKNR= checknr
-TEE= tee
-TR= tr
-TRUE= true
 
 
 ##################
@@ -86,8 +70,8 @@ C_STD= -std=gnu11
 
 # optimization and debug level
 #
-#COPT= -O3 -g3	# TODO - this will be the production release value - TODO #
-COPT= -O0 -g
+#C_OPT= -O3 -g3	# TODO - this will be the production release value - TODO #
+C_OPT= -O0 -g
 
 # Compiler warnings
 #
@@ -99,7 +83,7 @@ WARN_FLAGS= -Wall -Wextra -Werror
 #
 # We test by forcing warnings to be errors so you don't have to (allegedly :-) )
 #
-CFLAGS= ${C_STD} ${COPT} -pedantic ${WARN_FLAGS} ${LDFLAGS}
+CFLAGS= ${C_STD} ${C_OPT} -pedantic ${WARN_FLAGS} ${LDFLAGS}
 
 
 # NOTE: If you use ASAN, set this environment var:
@@ -117,7 +101,7 @@ CFLAGS= ${C_STD} ${COPT} -pedantic ${WARN_FLAGS} ${LDFLAGS}
 
 # where and what to install
 #
-DESTDIR= /usr/local/bin
+DEST_DIR= /usr/local/bin
 TARGETS= jnum_chk
 SH_TARGETS=
 
@@ -136,6 +120,10 @@ H_SRC= jnum_chk.h
 LESS_PICKY_CSRC=
 LESS_PICKY_HSRC=
 
+# all shell scripts
+#
+SH_FILES= jparse_test.sh jstr_test.sh
+
 
 ######################
 # intermediate files #
@@ -143,7 +131,7 @@ LESS_PICKY_HSRC=
 
 # NOTE: ${LIB_OBJS} are objects to put into a library and removed by make clean
 #
-LIB_OBJS=
+LIB_OBJS= jnum_chk.o jnum_test.o
 
 # NOTE: ${OTHER_OBJS} are objects NOT put into a library and removed by make clean
 #
@@ -163,7 +151,7 @@ ALL_OBJS= ${LIB_OBJS} ${OTHER_OBJS}
 #
 ALL_CSRC= ${C_SRC} ${LESS_PICKY_CSRC} ${BUILT_C_SRC}
 ALL_HSRC= ${H_SRC} ${LESS_PICKY_HSRC} ${BUILT_H_SRC}
-ALL_SRC= ${ALL_CSRC} ${ALL_HSRC}
+ALL_SRC= ${ALL_CSRC} ${ALL_HSRC} ${SH_FILES}
 
 
 #######################
@@ -284,10 +272,76 @@ test_JSON/auth.json/good/auth.reference.json:
 test: all jparse_test.sh
 	 ./jparse_test.sh -j ../jparse -d ./test_JSON ./json_teststr.txt
 
+# sequence exit codes
+#
+seqcexit: ${ALL_CSRC}
+	@HAVE_SEQCEXIT="`type -P ${SEQCEXIT}`"; if [[ -z "$$HAVE_SEQCEXIT" ]]; then \
+	    echo 'The seqcexit tool could not be found.' 1>&2; \
+	    echo 'The seqcexit tool is required for this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for seqcexit:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/lcn2/seqcexit'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}"; \
+	    ${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}; \
+	fi
+
+picky: ${ALL_SRC}
+	@if ! type -P ${PICKY} >/dev/null 2>&1; then \
+	    echo "The picky tool could not be found." 1>&2; \
+	    echo "The picky tool is required for this rule." 1>&2; \
+	    echo "We recommend you install picky v2.6 or later" 1>&2; \
+	    echo "from this URL:" 1>&2; \
+	    echo 1>&2; \
+	    echo "http://grail.eecs.csuohio.edu/~somos/picky.html" 1>&2; \
+	    echo 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}"; \
+	    ${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}; EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[1]: $$EXIT_CODE" 1>&2; exit 1; fi; \
+	    echo "${PICKY} -w -u -s -t8 -v -e -8 -- ${SH_FILES}"; \
+	    ${PICKY} -w -u -s -t8 -v -e -8 -- ${SH_FILES}; EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[2]: $$EXIT_CODE" 1>&2; exit 2; fi; \
+	fi
+
+# inspect and verify shell scripts
+#
+shellcheck: ${SH_FILES} .shellcheckrc
+	@HAVE_SHELLCHECK="`type -P ${SHELLCHECK}`"; if [[ -z "$$HAVE_SHELLCHECK" ]]; then \
+	    echo 'The shellcheck command could not be found.' 1>&2; \
+	    echo 'The shellcheck command is required to run this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for shellcheck:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/koalaman/shellcheck.net'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'Or use the package manager in your OS to install it.' 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${SHELLCHECK} -f gcc -- ${SH_FILES}"; \
+	    ${SHELLCHECK} -f gcc -- ${SH_FILES}; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[1]: $$EXIT_CODE" 1>&2; exit 1; fi; \
+	fi
+
+# inspect and verify man pages
+#
+check_man:
+	@:
+
+# vi/vim tags
+#
+tags: ${ALL_CSRC} ${ALL_HSRC}
+	-${CTAGS} ${ALL_CSRC} ${ALL_HSRC} 2>&1 | \
+	     ${GREP} -E -v 'Duplicate entry|Second entry ignored'
+
 prep_clean: legacy_clean
 	${RM} -f jnum_chk.o jnum_gen.o
 
-prep_clobber: legacy_clobber
+prep_clobber: prep_clean legacy_clobber
 	${RM} -f jstr_test.out jstr_test2.out
 	${RM} -f jnum_chk jnum_gen
 	${RM} -rf jnum_chk.dSYM
@@ -296,7 +350,7 @@ prep_clobber: legacy_clobber
 legacy_clean:
 	@:
 
-legacy_clobber:
+legacy_clobber: legacy_clean
 	@:
 
 
@@ -308,11 +362,12 @@ configure:
 	@echo nothing to $@
 
 clean:
-	${RM} -f jnum_chk.o jnum_test.o
+	${RM} -f ${ALL_OBJS} ${ALL_BUILT_SRC}
 
 clobber: clean
 	${RM} -f ${TARGETS}
 	${RM} -f jparse_test.log chkentry_test.log txzchk_test.log
+	${RM} -f tags
 
 install: all
 	@echo nothing to $@
diff --git a/soup/Makefile b/soup/Makefile
--- a/soup/Makefile
+++ b/soup/Makefile
@@ -39,11 +39,16 @@
 AR= ar
 CC= cc
 CMP= cmp
+CTAGS= ctags
+GREP= grep
 MAKE= make
+PICKY= picky
 RANLIB= ranlib
 RM= rm
 SED= sed
+SEQCEXIT= seqcexit
 SHELL= bash
+SHELLCHECK= shellcheck
 SLEEP= sleep
 TOUCH= touch
 
@@ -109,6 +114,10 @@ H_SRC= chk_validate.h soup.h
 LESS_PICKY_CSRC=
 LESS_PICKY_HSRC=
 
+# all shell scripts
+#
+SH_FILES= all_ref.sh fmt_depend.sh
+
 
 ######################
 # intermediate files #
@@ -136,7 +145,7 @@ ALL_OBJS= ${LIB_OBJS} ${OTHER_OBJS}
 #
 ALL_CSRC= ${C_SRC} ${LESS_PICKY_CSRC} ${BUILT_C_SRC}
 ALL_HSRC= ${H_SRC} ${LESS_PICKY_HSRC} ${BUILT_H_SRC}
-ALL_SRC= ${ALL_CSRC} ${ALL_HSRC}
+ALL_SRC= ${ALL_CSRC} ${ALL_HSRC} ${SH_FILES}
 
 
 #######################
@@ -383,16 +392,82 @@ eat eating eat_soup eating_soup: all
 	    echo "How can you eat soup that you haven't made yet?"; \
 	fi
 
+# sequence exit codes
+#
+seqcexit: ${ALL_CSRC}
+	@HAVE_SEQCEXIT="`type -P ${SEQCEXIT}`"; if [[ -z "$$HAVE_SEQCEXIT" ]]; then \
+	    echo 'The seqcexit tool could not be found.' 1>&2; \
+	    echo 'The seqcexit tool is required for this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for seqcexit:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/lcn2/seqcexit'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}"; \
+	    ${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}; \
+	fi
+
+picky: ${ALL_SRC}
+	@if ! type -P ${PICKY} >/dev/null 2>&1; then \
+	    echo "The picky tool could not be found." 1>&2; \
+	    echo "The picky tool is required for this rule." 1>&2; \
+	    echo "We recommend you install picky v2.6 or later" 1>&2; \
+	    echo "from this URL:" 1>&2; \
+	    echo 1>&2; \
+	    echo "http://grail.eecs.csuohio.edu/~somos/picky.html" 1>&2; \
+	    echo 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}"; \
+	    ${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}; EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[1]: $$EXIT_CODE" 1>&2; exit 1; fi; \
+	    echo "${PICKY} -w -u -s -t8 -v -e -8 -- ${SH_FILES}"; \
+	    ${PICKY} -w -u -s -t8 -v -e -8 -- ${SH_FILES}; EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[2]: $$EXIT_CODE" 1>&2; exit 2; fi; \
+	fi
+
+# inspect and verify shell scripts
+#
+shellcheck: ${SH_FILES} .shellcheckrc
+	@HAVE_SHELLCHECK="`type -P ${SHELLCHECK}`"; if [[ -z "$$HAVE_SHELLCHECK" ]]; then \
+	    echo 'The shellcheck command could not be found.' 1>&2; \
+	    echo 'The shellcheck command is required to run this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for shellcheck:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/koalaman/shellcheck.net'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'Or use the package manager in your OS to install it.' 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${SHELLCHECK} -f gcc -- ${SH_FILES}"; \
+	    ${SHELLCHECK} -f gcc -- ${SH_FILES}; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[1]: $$EXIT_CODE" 1>&2; exit 1; fi; \
+	fi
+
+# inspect and verify man pages
+#
+check_man:
+	@:
+
+# vi/vim tags
+#
+tags: ${ALL_CSRC} ${ALL_HSRC}
+	-${CTAGS} ${ALL_CSRC} ${ALL_HSRC} 2>&1 | \
+	     ${GREP} -E -v 'Duplicate entry|Second entry ignored'
+
 prep_clean: legacy_clean
 	@:
 
-prep_clobber: legacy_clobber
+prep_clobber: prep_clean legacy_clobber
 	${RM} -rf ref
 
 legacy_clean:
 	@:
 
-legacy_clobber:
+legacy_clobber: legacy_clean
 	@:
 
 
@@ -408,6 +483,7 @@ clean:
 
 clobber: clean
 	${RM} -f .soup
+	${RM} -f tags
 
 install: all
 	@echo "nothing to $@. Try eating soup instead."
diff --git a/test_ioccc/Makefile b/test_ioccc/Makefile
--- a/test_ioccc/Makefile
+++ b/test_ioccc/Makefile
@@ -36,37 +36,15 @@
 #	      Do not list shell builtin (echo, cd, ...) tools.
 #	      Keep the list in alphabetical order.
 #
-AWK= awk
-BASENAME= basename
-CAT= cat
 CC= cc
-CHECKNR= checknr
 CMP= cmp
-CP= cp
-CTAGS= ctags
-CUT= cut
-DIFF= diff
-FMT= fmt
-GIT= git
-GREP= grep
-HEAD= head
-INSTALL= install
 MAKE= make
-MAN2HTML= man2html
-MAN= man
-MKTEMP= mktemp
-MV= mv
 PICKY= picky
 RM= rm
-RPL= rpl
-RSYNC= rsync
 SED= sed
 SEQCEXIT= seqcexit
 SHELL= bash
 SHELLCHECK= shellcheck
-TEE= tee
-TR= tr
-TRUE= true
 
 
 ##################
@@ -99,8 +77,8 @@ C_STD= -std=gnu11
 
 # optimization and debug level
 #
-#COPT= -O3 -g3	# TODO - this will be the production release value - TODO #
-COPT= -O0 -g
+#C_OPT= -O3 -g3	# TODO - this will be the production release value - TODO #
+C_OPT= -O0 -g
 
 # Compiler warnings
 #
@@ -111,7 +89,7 @@ WARN_FLAGS= -Wall -Wextra -Werror
 #
 # We test by forcing warnings to be errors so you don't have to (allegedly :-) )
 #
-CFLAGS= ${C_STD} ${COPT} -pedantic ${WARN_FLAGS} ${LDFLAGS}
+CFLAGS= ${C_STD} ${C_OPT} -pedantic ${WARN_FLAGS} ${LDFLAGS}
 
 # NOTE: If you use ASAN, set this environment var:
 #	ASAN_OPTIONS="detect_stack_use_after_return=1"
@@ -141,6 +119,10 @@ H_SRC=
 LESS_PICKY_CSRC=
 LESS_PICKY_HSRC=
 
+# all shell scripts
+#
+SH_FILES= chkentry_test.sh ioccc_test.sh iocccsize_test.sh mkiocccentry_test.sh txzchk_test.sh
+
 
 ######################
 # intermediate files #
@@ -168,7 +150,7 @@ ALL_OBJS= ${LIB_OBJS} ${OTHER_OBJS}
 #
 ALL_CSRC= ${C_SRC} ${LESS_PICKY_CSRC} ${BUILT_C_SRC}
 ALL_HSRC= ${H_SRC} ${LESS_PICKY_HSRC} ${BUILT_H_SRC}
-ALL_SRC= ${ALL_CSRC} ${ALL_HSRC}
+ALL_SRC= ${ALL_CSRC} ${ALL_HSRC} ${SH_FILES}
 
 
 #######################
@@ -208,7 +190,7 @@ EXTERN_CLOBBER= ${EXTERN_O} ${EXTERN_LIBA} ${EXTERN_PROG}
 
 # where and what to install
 #
-DESTDIR= /usr/local/bin
+DEST_DIR= /usr/local/bin
 TARGETS= utf8_test
 SH_TARGETS=
 
@@ -298,16 +280,82 @@ ioccc_test.sh: ../dbg/dbg_test ../dyn_array/dyn_test
 test: all ioccc_test.sh
 	 ./ioccc_test.sh
 
+# sequence exit codes
+#
+seqcexit: ${ALL_CSRC}
+	@HAVE_SEQCEXIT="`type -P ${SEQCEXIT}`"; if [[ -z "$$HAVE_SEQCEXIT" ]]; then \
+	    echo 'The seqcexit tool could not be found.' 1>&2; \
+	    echo 'The seqcexit tool is required for this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for seqcexit:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/lcn2/seqcexit'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}"; \
+	    ${SEQCEXIT} -D werr_sem_val -D werrp_sem_val -- ${ALL_CSRC}; \
+	fi
+
+picky: ${ALL_SRC}
+	@if ! type -P ${PICKY} >/dev/null 2>&1; then \
+	    echo "The picky tool could not be found." 1>&2; \
+	    echo "The picky tool is required for this rule." 1>&2; \
+	    echo "We recommend you install picky v2.6 or later" 1>&2; \
+	    echo "from this URL:" 1>&2; \
+	    echo 1>&2; \
+	    echo "http://grail.eecs.csuohio.edu/~somos/picky.html" 1>&2; \
+	    echo 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}"; \
+	    ${PICKY} -w132 -u -s -t8 -v -e -- ${C_SRC} ${H_SRC}; EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[1]: $$EXIT_CODE" 1>&2; exit 1; fi; \
+	    echo "${PICKY} -w -u -s -t8 -v -e -8 -- ${SH_FILES}"; \
+	    ${PICKY} -w -u -s -t8 -v -e -8 -- ${SH_FILES}; EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[2]: $$EXIT_CODE" 1>&2; exit 2; fi; \
+	fi
+
+# inspect and verify shell scripts
+#
+shellcheck: ${SH_FILES} .shellcheckrc
+	@HAVE_SHELLCHECK="`type -P ${SHELLCHECK}`"; if [[ -z "$$HAVE_SHELLCHECK" ]]; then \
+	    echo 'The shellcheck command could not be found.' 1>&2; \
+	    echo 'The shellcheck command is required to run this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for shellcheck:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/koalaman/shellcheck.net'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'Or use the package manager in your OS to install it.' 1>&2; \
+	    exit 1; \
+	else \
+	    echo "${SHELLCHECK} -f gcc -- ${SH_FILES}"; \
+	    ${SHELLCHECK} -f gcc -- ${SH_FILES}; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then echo "make $@: ERROR: CODE[1]: $$EXIT_CODE" 1>&2; exit 1; fi; \
+	fi
+
+# inspect and verify man pages
+#
+check_man:
+	@:
+
+# vi/vim tags
+#
+tags: ${ALL_CSRC} ${ALL_HSRC}
+	@:
+
 prep_clean: legacy_clean
 	@:
 
-prep_clobber: legacy_clobber
+prep_clobber: prep_clean legacy_clobber
 	${RM} -rf test_iocccsize test_src test_work
+	${RM} -f utf8_test
 
 legacy_clean:
 	${RM} -f jint.test.o jfloat.test.o
 
-legacy_clobber:
+legacy_clobber: legacy_clean
 	${RM} -f jparse_test.log jint.test jfloat.test
 
 
