improve make depend
The depend rule checks for independ tool.  If found, it will
use it in the action, otherwise it will inform the user
and where the tool may be obtained without exiting non-zero.

diff --git a/dbg/Makefile b/dbg/Makefile
--- a/dbg/Makefile
+++ b/dbg/Makefile
@@ -548,20 +548,36 @@ depend: ${ALL_CSRC} all
 	@echo
 	@echo "${OUR_NAME}: make $@ starting"
 	@echo
-	@${SED} -i.orig -n -e '1,/^### DO NOT CHANGE MANUALLY BEYOND THIS LINE/p' Makefile
-	${CC} ${CFLAGS} -MM ${ALL_CSRC} | ${INDEPEND} >> Makefile
-	@-if ${CMP} -s Makefile.orig Makefile; then \
-	    ${RM} -f Makefile.orig; \
+	@HAVE_INDEPEND="`type -P ${INDEPEND}`"; if [[ -z "$$HAVE_INDEPEND" ]]; then \
+	    echo 'The independ command could not be found.' 1>&2; \
+	    echo 'The independ command is required to run this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for where to obtain independ:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/lcn2/independ'; 1>&2; \
+	    echo ''; 1>&2; \
 	else \
-	    echo; \
-	    echo "${OUR_NAME}: Makefile dependencies updated"; \
-	    echo; \
-	    echo "${OUR_NAME}: Previous version may be found in: Makefile.orig"; \
+	    @${SED} -i.orig -n -e '1,/^### DO NOT CHANGE MANUALLY BEYOND THIS LINE/p' Makefile; \
+	    ${CC} ${CFLAGS} -MM -I. -DMKIOCCCENTRY_USE ${ALL_CSRC} | ${INDEPEND} >> Makefile; \
+	    if ${CMP} -s Makefile.orig Makefile; then \
+		${RM} -f Makefile.orig; \
+	    else \
+		echo; \
+		echo "${OUR_NAME}: Makefile dependencies updated"; \
+		echo; \
+		echo "${OUR_NAME}: Previous version may be found in: Makefile.orig"; \
+	    fi; \
 	fi
 	@echo
 	@echo "${OUR_NAME}: make $@ complete"
 
 ### DO NOT CHANGE MANUALLY BEYOND THIS LINE
+dbg.o: dbg.c dbg.h
+dbg_example.o: dbg.h dbg_example.c
+dbg_test.o: dbg.h dbg_test.c
+dbg.o: dbg.c dbg.h
+dbg_example.o: dbg.h dbg_example.c
+dbg_test.o: dbg.h dbg_test.c
 dbg.o: dbg.c dbg.h
 dbg_example.o: dbg.h dbg_example.c
 dbg_test.o: dbg.h dbg_test.c
diff --git a/jparse/Makefile b/jparse/Makefile
--- a/jparse/Makefile
+++ b/jparse/Makefile
@@ -777,21 +777,62 @@ depend: ${ALL_CSRC} all
 	@echo
 	@echo "${OUR_NAME}: make $@ starting"
 	@echo
-	@${SED} -i.orig -n -e '1,/^### DO NOT CHANGE MANUALLY BEYOND THIS LINE/p' Makefile
-	${CC} ${CFLAGS} -MM -I../dbg -I../dyn_array -I.. ${ALL_CSRC} | ${INDEPEND} >> Makefile
-	@-if ${CMP} -s Makefile.orig Makefile; then \
-	    ${RM} -f Makefile.orig; \
+	@HAVE_INDEPEND="`type -P ${INDEPEND}`"; if [[ -z "$$HAVE_INDEPEND" ]]; then \
+	    echo 'The independ command could not be found.' 1>&2; \
+	    echo 'The independ command is required to run this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for where to obtain independ:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/lcn2/independ'; 1>&2; \
+	    echo ''; 1>&2; \
 	else \
-	    echo; \
-	    echo "${OUR_NAME}: Makefile dependencies updated"; \
-	    echo; \
-	    echo "${OUR_NAME}: Previous version may be found in: Makefile.orig"; \
+	    @${SED} -i.orig -n -e '1,/^### DO NOT CHANGE MANUALLY BEYOND THIS LINE/p' Makefile; \
+	    ${CC} ${CFLAGS} -MM -I. -DMKIOCCCENTRY_USE ${ALL_CSRC} | ${INDEPEND} >> Makefile; \
+	    if ${CMP} -s Makefile.orig Makefile; then \
+		${RM} -f Makefile.orig; \
+	    else \
+		echo; \
+		echo "${OUR_NAME}: Makefile dependencies updated"; \
+		echo; \
+		echo "${OUR_NAME}: Previous version may be found in: Makefile.orig"; \
+	    fi; \
 	fi
 	@echo
 	@echo "${OUR_NAME}: make $@ complete"
 	${MAKE} -C test_jparse $@
 
 ### DO NOT CHANGE MANUALLY BEYOND THIS LINE
+jnum_gen.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h ../dyn_array/dyn_array.h \
+    jnum_gen.c jnum_gen.h json_parse.h json_util.h util.h
+jnum_header.o: ../dyn_array/../dbg/dbg.h ../dyn_array/dyn_array.h \
+    jnum_header.c json_parse.h util.h
+jparse.ref.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h \
+    ../dyn_array/dyn_array.h jparse.h jparse.ref.c jparse.tab.h \
+    json_parse.h json_sem.h json_util.h util.h
+jparse.tab.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h \
+    ../dyn_array/dyn_array.h jparse.h jparse.lex.h jparse.tab.c \
+    jparse.tab.h json_parse.h json_sem.h json_util.h util.h
+jparse.tab.ref.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h \
+    ../dyn_array/dyn_array.h jparse.h jparse.lex.h jparse.tab.h \
+    jparse.tab.ref.c json_parse.h json_sem.h json_util.h util.h
+jparse_main.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h \
+    ../dyn_array/dyn_array.h jparse.h jparse.tab.h jparse_main.c \
+    jparse_main.h json_parse.h json_sem.h json_util.h util.h
+jsemtblgen.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h \
+    ../dyn_array/dyn_array.h ../iocccsize.h jparse.h jparse.tab.h \
+    jsemtblgen.c jsemtblgen.h json_parse.h json_sem.h json_util.h util.h
+json_parse.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h \
+    ../dyn_array/dyn_array.h json_parse.c json_parse.h json_util.h util.h
+json_sem.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h ../dyn_array/dyn_array.h \
+    json_parse.h json_sem.c json_sem.h json_util.h util.h
+json_util.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h \
+    ../dyn_array/dyn_array.h json_parse.h json_util.c json_util.h util.h
+jstrdecode.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h \
+    ../dyn_array/dyn_array.h json_parse.h jstrdecode.c jstrdecode.h util.h
+jstrencode.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h \
+    ../dyn_array/dyn_array.h json_parse.h jstrencode.c jstrencode.h util.h
+util.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h ../dyn_array/dyn_array.h \
+    util.c util.h
 jnum_gen.o: ../dbg/dbg.h ../dyn_array/../dbg/dbg.h ../dyn_array/dyn_array.h \
     jnum_gen.c jnum_gen.h json_parse.h json_util.h util.h
 jnum_header.o: ../dyn_array/../dbg/dbg.h ../dyn_array/dyn_array.h \
diff --git a/test_ioccc/Makefile b/test_ioccc/Makefile
--- a/test_ioccc/Makefile
+++ b/test_ioccc/Makefile
@@ -484,20 +484,43 @@ depend: ${ALL_CSRC} all
 	@echo
 	@echo "${OUR_NAME}: make $@ starting"
 	@echo
-	@${SED} -i.orig -n -e '1,/^### DO NOT CHANGE MANUALLY BEYOND THIS LINE/p' Makefile
-	${CC} ${CFLAGS} -MM ${ALL_CSRC} | ${INDEPEND} >> Makefile
-	@-if ${CMP} -s Makefile.orig Makefile; then \
-	    ${RM} -f Makefile.orig; \
+	@HAVE_INDEPEND="`type -P ${INDEPEND}`"; if [[ -z "$$HAVE_INDEPEND" ]]; then \
+	    echo 'The independ command could not be found.' 1>&2; \
+	    echo 'The independ command is required to run this rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'See the following GitHub repo for where to obtain independ:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/lcn2/independ'; 1>&2; \
+	    echo ''; 1>&2; \
 	else \
-	    echo; \
-	    echo "${OUR_NAME}: Makefile dependencies updated"; \
-	    echo; \
-	    echo "${OUR_NAME}: Previous version may be found in: Makefile.orig"; \
+	    @${SED} -i.orig -n -e '1,/^### DO NOT CHANGE MANUALLY BEYOND THIS LINE/p' Makefile; \
+	    ${CC} ${CFLAGS} -MM -I. -DMKIOCCCENTRY_USE ${ALL_CSRC} | ${INDEPEND} >> Makefile; \
+	    if ${CMP} -s Makefile.orig Makefile; then \
+		${RM} -f Makefile.orig; \
+	    else \
+		echo; \
+		echo "${OUR_NAME}: Makefile dependencies updated"; \
+		echo; \
+		echo "${OUR_NAME}: Previous version may be found in: Makefile.orig"; \
+	    fi; \
 	fi
 	@echo
 	@echo "${OUR_NAME}: make $@ complete"
 
 ### DO NOT CHANGE MANUALLY BEYOND THIS LINE
+fnamchk.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
+    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
+    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
+    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
+    ../soup/../dbg/dbg.h ../soup/../jparse/jparse.h ../soup/limit_ioccc.h \
+    ../soup/utf8_posix_map.h ../soup/version.h fnamchk.c fnamchk.h
+utf8_test.o: ../soup/../dbg/dbg.h ../soup/../jparse/../dbg/dbg.h \
+    ../soup/../jparse/../dyn_array/../dbg/dbg.h \
+    ../soup/../jparse/../dyn_array/dyn_array.h ../soup/../jparse/jparse.h \
+    ../soup/../jparse/jparse.tab.h ../soup/../jparse/json_parse.h \
+    ../soup/../jparse/json_sem.h ../soup/../jparse/json_util.h \
+    ../soup/../jparse/util.h ../soup/limit_ioccc.h ../soup/utf8_posix_map.h \
+    ../soup/version.h utf8_test.c
 fnamchk.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
     ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
     ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
