fix make test and add check_man to prep.sh
The `make test` does not depend, Makefile-wise, on any other rules.
It is now a standalone test.  Various Makefile actions for `make test`
perform a pre-check to determine if conditions are reasonable to
attempt the full test.  Thus, this does the right thing:

```bash
make clobber test
```

This does the right thing as well:

```bash
make all test
```

As does this:

```bash
make clobber all test
```

Added check_man action to prep.sh.

diff --git a/dbg/Makefile b/dbg/Makefile
--- a/dbg/Makefile
+++ b/dbg/Makefile
@@ -428,35 +428,30 @@ test:
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
 	${Q} ${RM} -f dbg_test.out
-	${V} echo "RUNNING: dbg_test"
-	${V} echo "./dbg_test -e 2 foo bar baz >dbg_test.out 2>&1"
-	${Q} if [[ ! -x ./dbg_test ]]; then \
-	    echo "${OUR_NAME}: executable not found: ./dbg_test" 1>&2; \
-	    echo "${OUR_NAME}: trying to make dbg_test" 1>&2; \
-	    ${MAKE} dbg_test; \
+	-${Q} if [[ ! -x ./dbg_test ]]; then \
+	    echo "${OUR_NAME}: ERROR: executable not found: ./dbg_test" 1>&2; \
+	    echo "${OUR_NAME}: ERROR: unable to perform complete test" 1>&2; \
+	else \
+	    echo "./dbg_test -e 2 foo bar baz >dbg_test.out 2>&1"; \
+	    ./dbg_test -v 1 -e 2 foo bar baz >dbg_test.out 2>&1; \
+	    EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 5 ]]; then \
+		echo "${OUR_NAME}: exit status of dbg_test: $$EXIT_CODE != 5"; \
+		exit 21; \
+	    else \
+		${GREP} -q '^ERROR\[5\]: main: simulated error, foo: foo bar: bar: errno\[2\]: No such file or directory$$' dbg_test.out; \
+		EXIT_CODE="$$?"; \
+		if [[ $$EXIT_CODE -ne 0 ]]; then \
+		    echo "${OUR_NAME}: ERROR: did not find the correct dbg_test error message" 1>&2; \
+		    echo "${OUR_NAME}: ERROR: beginning dbg_test.out contents" 1>&2; \
+		    ${CAT} dbg_test.out 1>&2; \
+		    echo "${OUR_NAME}: ERROR: dbg_test.out contents complete" 1>&2; \
+		    exit 22; \
+		else \
+		    echo "${OUR_NAME}: PASSED: dbg_test"; \
+		fi; \
+	    fi; \
 	fi
-	${Q} if [[ ! -x ./dbg_test ]]; then \
-	    echo "${OUR_NAME}: ERROR: unable to create excutable: ./dbg_test" 1>&2; \
-	    exit 20; \
-	fi
-	-${Q} ./dbg_test -v 1 -e 2 foo bar baz >dbg_test.out 2>&1; \
-	  EXIT_CODE="$$?"; \
-	  if [[ $$EXIT_CODE -ne 5 ]]; then \
-	    echo "${OUR_NAME}: exit status of dbg_test: $$EXIT_CODE != 5"; \
-	    exit 21; \
-	  else \
-	      ${GREP} -q '^ERROR\[5\]: main: simulated error, foo: foo bar: bar: errno\[2\]: No such file or directory$$' dbg_test.out; \
-	      EXIT_CODE="$$?"; \
-	      if [[ $$EXIT_CODE -ne 0 ]]; then \
-		echo "${OUR_NAME}: ERROR: did not find the correct dbg_test error message" 1>&2; \
-		echo "${OUR_NAME}: ERROR: beginning dbg_test.out contents" 1>&2; \
-		${CAT} dbg_test.out 1>&2; \
-		echo "${OUR_NAME}: ERROR: dbg_test.out contents complete" 1>&2; \
-		exit 22; \
-	      else \
-		echo "${OUR_NAME}: PASSED: dbg_test"; \
-	      fi; \
-	  fi
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ ending"
 
diff --git a/dyn_array/Makefile b/dyn_array/Makefile
--- a/dyn_array/Makefile
+++ b/dyn_array/Makefile
@@ -394,21 +394,19 @@ test:
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	${Q} if [[ ! -x ./dyn_test ]]; then \
-	    echo "${OUR_NAME}: executable not found: ./dyn_test" 1>&2; \
-	    echo "${OUR_NAME}: trying to make dyn_test" 1>&2; \
-	    ${MAKE} dyn_test; \
-	fi
-	${Q} if [[ ! -x ./dyn_test ]]; then \
-	    echo "${OUR_NAME}: ERROR: unable to create excutable: ./dyn_test" 1>&2; \
-	    exit 20; \
-	fi
-	-${Q} ./dyn_test; \
-	EXIT_CODE="$$?"; \
-	if [[ $$EXIT_CODE -ne 0 ]]; then \
-	    echo '${OUR_NAME}: ERROR: dyn_test failed, error code: $$EXIT_CODE'; \
+	-${Q} if [[ ! -x ./dyn_test ]]; then \
+	    echo "${OUR_NAME}: ERROR: executable not found: ./dyn_test" 1>&2; \
+	    echo "${OUR_NAME}: ERROR: unable to perform complete test" 1>&2; \
 	else \
-	    echo ${OUR_NAME}: "PASSED: dyn_test"; \
+	    echo ./dyn_test; \
+	    ./dyn_test; \
+	    EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then \
+		echo "${OUR_NAME}: ERROR: dyn_test failed, error code: $$EXIT_CODE"; \
+		exit "$$EXIT_CODE"; \
+	    else \
+		echo ${OUR_NAME}: "PASSED: dyn_test"; \
+	    fi; \
 	fi
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ ending"
diff --git a/jparse/test_jparse/Makefile b/jparse/test_jparse/Makefile
--- a/jparse/test_jparse/Makefile
+++ b/jparse/test_jparse/Makefile
@@ -342,11 +342,24 @@ test_JSON/auth.json/good/auth.reference.json:
 # repo tools - rules for those who maintain the this repo #
 ###########################################################
 
-test: jparse_test.sh
+test:
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	${Q} ./jparse_test.sh -j ../jparse -d test_JSON -s . ./json_teststr.txt
+	-${Q} if [[ ! -x ./jparse_test.sh ]]; then \
+	    echo "${OUR_NAME}: ERROR: executable not found: ./jparse_test.sh" 1>&2; \
+	    echo "${OUR_NAME}: ERROR: unable to perform complete test" 1>&2; \
+	else \
+	    echo "./jparse_test.sh -j ../jparse -d test_JSON -s . ./json_teststr.txt"; \
+	    ./jparse_test.sh -j ../jparse -d test_JSON -s . ./json_teststr.txt; \
+	    EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then \
+		echo "${OUR_NAME}: ERROR: jparse_test.sh failed, error code: $$EXIT_CODE"; \
+		exit "$$EXIT_CODE"; \
+	    else \
+		echo ${OUR_NAME}: "PASSED: jparse_test.sh"; \
+	    fi; \
+	fi
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ ending"
 
diff --git a/test_ioccc/Makefile b/test_ioccc/Makefile
--- a/test_ioccc/Makefile
+++ b/test_ioccc/Makefile
@@ -379,11 +379,24 @@ fnamchk: fnamchk.o ../jparse/jparse.a ../dyn_array/dyn_array.a ../dbg/dbg.a
 # repo tools - rules for those who maintain the this repo #
 ###########################################################
 
-test: ioccc_test.sh
+test:
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	${Q} ./ioccc_test.sh
+	-${Q} if [[ ! -x ./ioccc_test.sh ]]; then \
+	    echo "${OUR_NAME}: ERROR: executable not found: .//ioccc_test.sh" 1>&2; \
+	    echo "${OUR_NAME}: ERROR: unable to perform complete test" 1>&2; \
+	else \
+	    echo ./ioccc_test.sh; \
+	    ./ioccc_test.sh; \
+	    EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then \
+		echo "${OUR_NAME}: ERROR: ioccc_test.s failed, error code: $$EXIT_CODE"; \
+		exit "$$EXIT_CODE"; \
+	    else \
+		echo ${OUR_NAME}: "PASSED: ioccc_test.sh"; \
+	    fi; \
+	fi
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ ending"
 
