improve tags related rules
Test if ctags is available before attempting to run ctags
in Makefile rules.

diff --git a/dbg/Makefile b/dbg/Makefile
--- a/dbg/Makefile
+++ b/dbg/Makefile
@@ -550,6 +550,17 @@ tags: ${ALL_CSRC} ${ALL_HSRC}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
+	${Q} if ! type -P ${CTAGS} >/dev/null 2>&1; then \
+	    echo 'The ${CTAGS} command could not be found.' 1>&2; \
+	    echo 'The ${CTAGS} command is required to run the $@ rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'Use the package manager from your OS to install the ${CTAGS} package.' 1>&2; \
+	    echo 'The following GitHub repo may be a useful ${CTAGS} alternative:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/universal-ctags/ctags'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	fi
 	${E} ${MAKE} local_dir_tags
 	${Q} echo
 	${E} ${MAKE} all_tags
@@ -562,6 +573,17 @@ local_dir_tags: ${ALL_CSRC} ${ALL_HSRC}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
+	${Q} if ! type -P ${CTAGS} >/dev/null 2>&1; then \
+	    echo 'The ${CTAGS} command could not be found.' 1>&2; \
+	    echo 'The ${CTAGS} command is required to run the $@ rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'Use the package manager from your OS to install the ${CTAGS} package.' 1>&2; \
+	    echo 'The following GitHub repo may be a useful ${CTAGS} alternative:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/universal-ctags/ctags'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	fi
 	${Q} ${RM} -f ${LOCAL_DIR_TAGS}
 	-${E} ${CTAGS} -w -f ${LOCAL_DIR_TAGS} ${ALL_CSRC} ${ALL_HSRC}
 	${S} echo
diff --git a/jparse/Makefile b/jparse/Makefile
--- a/jparse/Makefile
+++ b/jparse/Makefile
@@ -769,6 +769,17 @@ tags:
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
+	${Q} if ! type -P ${CTAGS} >/dev/null 2>&1; then \
+	    echo 'The ${CTAGS} command could not be found.' 1>&2; \
+	    echo 'The ${CTAGS} command is required to run the $@ rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'Use the package manager from your OS to install the ${CTAGS} package.' 1>&2; \
+	    echo 'The following GitHub repo may be a useful ${CTAGS} alternative:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/universal-ctags/ctags'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	fi
 	${Q} for dir in ../dbg ../dyn_alloc; do \
 	    if [[ -f $$dir/Makefile && ! -f $$dir/${LOCAL_DIR_TAGS} ]]; then \
 		echo ${MAKE} ${MAKE_CD_Q} -C $$dir local_dir_tags; \
@@ -788,6 +799,17 @@ local_dir_tags: ${ALL_CSRC} ${ALL_HSRC}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
+	${Q} if ! type -P ${CTAGS} >/dev/null 2>&1; then \
+	    echo 'The ${CTAGS} command could not be found.' 1>&2; \
+	    echo 'The ${CTAGS} command is required to run the $@ rule.'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo 'Use the package manager from your OS to install the ${CTAGS} package.' 1>&2; \
+	    echo 'The following GitHub repo may be a useful ${CTAGS} alternative:'; 1>&2; \
+	    echo ''; 1>&2; \
+	    echo '    https://github.com/universal-ctags/ctags'; 1>&2; \
+	    echo ''; 1>&2; \
+	    exit 1; \
+	fi
 	${E} ${MAKE} ${MAKE_CD_Q} -C test_jparse $@
 	${Q} echo
 	${Q} ${RM} -f ${LOCAL_DIR_TAGS}
