Improve Makefiles (consistency, fixes, other)
Change all lines like

    ${Q} HAVE_FOO="`type -P ${FOO}`"; if [[ -z "$$HAVE_FOO" ]]; then \

to

    ${Q} if ! type -P ${FOO} >/dev/null 2>&1; then \

Change wording of those rules so that they're all the same. This
includes in obtaining the tool, the required to run this rule text and
everything else. If it was fatal that the tool did not exist I kept it
fatal but otherwise it's ignored as it was before.

In the rules that refer to tools change the name of the tool to the
variable that is used to check for the tool itself (except in the URLs).

Due to a yank paste error the missing picky tool referred to seqcexit
rather than picky (not in the URL but in the text).

The rules changed are those for picky, seqcexit, checknr, shellcheck and
depend.

Running make release after these changes works well.

diff --git a/dbg/Makefile b/dbg/Makefile
--- a/dbg/Makefile
+++ b/dbg/Makefile
@@ -461,11 +461,11 @@ seqcexit: ${ALL_CSRC}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	${Q} HAVE_SEQCEXIT="`type -P ${SEQCEXIT}`"; if [[ -z "$$HAVE_SEQCEXIT" ]]; then \
-	    echo 'The seqcexit tool could not be found.' 1>&2; \
-	    echo 'The seqcexit tool is required for this rule.'; 1>&2; \
+	${Q} if ! type -P ${SEQCEXIT} >/dev/null 2>&1; then \
+	    echo 'The ${SEQCEXIT} tool could not be found.' 1>&2; \
+	    echo 'The ${SEQCEXIT} tool is required for the $@ rule.'; 1>&2; \
 	    echo ''; 1>&2; \
-	    echo 'See the following GitHub repo for seqcexit:'; 1>&2; \
+	    echo 'See the following GitHub repo for ${SEQCEXIT}:'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo '    https://github.com/lcn2/seqcexit'; 1>&2; \
 	    echo ''; 1>&2; \
@@ -482,12 +482,12 @@ picky: ${ALL_SRC}
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
 	${Q} if ! type -P ${PICKY} >/dev/null 2>&1; then \
-	    echo 'The picky tool could not be found.' 1>&2; \
-	    echo 'The picky tool is required for this rule.' 1>&2; \
+	    echo 'The ${PICKY} tool could not be found.' 1>&2; \
+	    echo 'The ${PICKY} tool is required for the $@ rule.' 1>&2; \
 	    echo 1>&2; \
-	    echo 'See the following GitHub repo for seqcexit:'; 1>&2; \
+	    echo 'See the following GitHub repo for ${PICKY}:'; 1>&2; \
 	    echo 1>&2; \
-	    echo "https://github.com/xexyl/picky" 1>&2; \
+	    echo '    https://github.com/xexyl/picky' 1>&2; \
 	    echo 1>&2; \
 	    exit 1; \
 	else \
@@ -518,25 +518,27 @@ check_man: ${ALL_MAN_TARGETS}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${S} echo
-	-${Q} HAVE_CHECKNR="`type -P ${CHECKNR}`"; if [[ -z "$$HAVE_CHECKNR" ]]; then \
-	    echo 'The checknr command could not be found.' 1>&2; \
-	    echo 'The checknr command is required to run the $@ rule.' 1>&2; \
+	-${Q} if ! type -P ${CHECKNR} >/dev/null 2>&1; then \
+	    echo 'The ${CHECKNR} command could not be found.' 1>&2; \
+	    echo 'The ${CHECKNR} command is required to run the $@ rule.' 1>&2; \
 	    echo ''; 1>&2; \
-	    echo 'The source code and install instructions for checknr are available from this GitHub repo:' 1>&2; \
+	    echo 'See the following GitHub repo for ${CHECKNR}:'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo '    https://github.com/lcn2/checknr' 1>&2; \
 	    echo ''; 1>&2; \
+	    echo 'Or use the package manager in your OS to install it.' 1>&2; \
 	else \
 	    echo "${CHECKNR} -c.BR.SS.BI ${ALL_MAN_TARGETS}"; \
 	    ${CHECKNR} -c.BR.SS.BI ${ALL_MAN_TARGETS}; \
 	    EXIT_CODE="$$?"; \
 	    if [[ $$EXIT_CODE -ne 0 ]]; then \
-		echo 'ERROR: checknr: ${CHECKNR} failed, error code: $$EXIT_CODE'; \
+		echo 'ERROR: check_man: ${CHECKNR} failed, error code: $$EXIT_CODE'; \
 		exit 23; \
 	    fi; \
 	fi
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ ending"
+
 
 # install man pages
 #
@@ -618,11 +620,11 @@ install: all install_man
 depend: ${ALL_CSRC}
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
-	${Q} HAVE_INDEPEND="`type -P ${INDEPEND}`"; if [[ -z "$$HAVE_INDEPEND" ]]; then \
-	    echo '${OUR_NAME}: The independ command could not be found.' 1>&2; \
-	    echo '${OUR_NAME}: The independ command is required to perform: make $@'; 1>&2; \
+	${Q} if ! type -P ${INDEPEND} >/dev/null 2>&1; then \
+	    echo '${OUR_NAME}: The ${INDEPEND} command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The ${INDEPEND} command is required to run the $@ rule'; 1>&2; \
 	    echo ''; 1>&2; \
-	    echo 'See the following GitHub repo for where to obtain independ:'; 1>&2; \
+	    echo 'See the following GitHub repo for ${INDEPEND}:'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo '    https://github.com/lcn2/independ'; 1>&2; \
 	else \
