Sync jparse one more time before freeze
Synced jparse from jparse repo (https://github.com/xexyl/jparse/). This
includes better (additional) testing of JSON encoding/decoding ('Beware
of the <del>dragon</del> fire drake[0]
(https://www.glyphweb.com/arda/f/firedrakes.html)!' :-) ), a new version
string (UTF-8 version, which is now also displayed in the tools in this
repo, as it also helps identify if there is a mismatch in versions in
bug reporting or something else), amongst various other things.  Should
one wish to further progress their dementia! :-) they can look at that
repo's log or the jparse/CHANGES.md file.

[0] Now given that it's for a code freeze, the question is why not cold
drakes? Well one can look at the code, or perhaps the output of a
certain option to two tools in jparse, for the answer to that! :-)

diff --git a/jparse/test_jparse/Makefile b/jparse/test_jparse/Makefile
--- a/jparse/test_jparse/Makefile
+++ b/jparse/test_jparse/Makefile
@@ -359,7 +359,7 @@ jnum_gen.o: jnum_gen.c jnum_gen.h ../json_utf8.h ../version.h
 jnum_gen: jnum_gen.o ../libjparse.a
 	${CC} ${CFLAGS} $^ -lm -o $@ ${LD_DIR2} -ldyn_array -ldbg
 
-pr_jparse_test.o: pr_jparse_test.c pr_jparse_test.h ../version.h
+pr_jparse_test.o: pr_jparse_test.c pr_jparse_test.h ../json_utf8.h ../version.h
 	${CC} ${CFLAGS} pr_jparse_test.c -c
 
 pr_jparse_test: pr_jparse_test.o ../libjparse.a
@@ -429,6 +429,16 @@ test:
 	else \
 	    echo "${OUR_NAME}: RUNNING: ./jparse_test.sh -v ${VERBOSITY} -j ./jparse -p test_jparse/pr_jparse_test -d test_jparse/test_JSON -s . test_jparse/json_teststr.txt"; \
 	    ./jparse_test.sh -v ${VERBOSITY} -j ./jparse -p test_jparse/pr_jparse_test -d test_jparse/test_JSON -s . test_jparse/json_teststr.txt; \
+	    EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then \
+		echo "${OUR_NAME}: ERROR: jparse_test.sh failed, error code: $$EXIT_CODE"; \
+		exit "$$EXIT_CODE"; \
+	    else \
+		echo "${OUR_NAME}: PASSED: jparse_test.sh"; \
+	    fi; \
+	    echo; \
+	    echo "${OUR_NAME}: RUNNING:  ./jparse_test.sh -v ${VERBOSITY} -j ./jparse -F jparse.json"; \
+	    ./jparse_test.sh -v ${VERBOSITY} -j ./jparse -F jparse.json; \
 	    EXIT_CODE="$$?"; \
 	    if [[ $$EXIT_CODE -ne 0 ]]; then \
 		echo "${OUR_NAME}: ERROR: jparse_test.sh failed, error code: $$EXIT_CODE"; \
