fix make depend
Test if the "DO NOT CHANGE MANUALLY" line exits (exit 1
if it does not), and perform the Makefile update if needed.

Do not depend on Makefiles for make depend.

diff --git a/jparse/test_jparse/Makefile b/jparse/test_jparse/Makefile
--- a/jparse/test_jparse/Makefile
+++ b/jparse/test_jparse/Makefile
@@ -474,22 +474,23 @@ install: all
 depend: ${ALL_CSRC} all
 	@echo
 	@echo "${OUR_NAME}: make $@ starting"
-	@echo
 	@HAVE_INDEPEND="`type -P ${INDEPEND}`"; if [[ -z "$$HAVE_INDEPEND" ]]; then \
-	    echo 'The independ command could not be found.' 1>&2; \
-	    echo 'The independ command is required to run this rule.'; 1>&2; \
+	    echo '${OUR_NAME}: The independ command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The independ command is required to perform: make $@'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo 'See the following GitHub repo for where to obtain independ:'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo '    https://github.com/lcn2/independ'; 1>&2; \
-	    echo ''; 1>&2; \
 	else \
-	    @${SED} -i.orig -n -e '1,/^### DO NOT CHANGE MANUALLY BEYOND THIS LINE/p' Makefile; \
+	    if ! ${GREP} -q '^### DO NOT CHANGE MANUALLY BEYOND THIS LINE$$' Makefile; then \
+	        echo "${OUR_NAME}: make $@ aborting, Makefile missing: ### DO NOT CHANGE MANUALLY BEYOND THIS LINE" 1>&2; \
+		exit 1; \
+	    fi; \
+	    ${SED} -i.orig -n -e '1,/^### DO NOT CHANGE MANUALLY BEYOND THIS LINE$$/p' Makefile; \
 	    ${CC} ${CFLAGS} -MM -I. -DMKIOCCCENTRY_USE ${ALL_CSRC} | ${INDEPEND} >> Makefile; \
 	    if ${CMP} -s Makefile.orig Makefile; then \
 		${RM} -f Makefile.orig; \
 	    else \
-		echo; \
 		echo "${OUR_NAME}: Makefile dependencies updated"; \
 		echo; \
 		echo "${OUR_NAME}: Previous version may be found in: Makefile.orig"; \
@@ -499,20 +500,6 @@ depend: ${ALL_CSRC} all
 	@echo "${OUR_NAME}: make $@ complete"
 
 ### DO NOT CHANGE MANUALLY BEYOND THIS LINE
-jnum_chk.o: ../../dbg/dbg.h ../../dyn_array/../dbg/dbg.h \
-    ../../dyn_array/dyn_array.h ../../jparse/json_parse.h \
-    ../../jparse/json_util.h ../json_parse.h ../util.h jnum_chk.c \
-    jnum_chk.h
-jnum_test.o: ../../jparse/../dyn_array/../dbg/dbg.h \
-    ../../jparse/../dyn_array/dyn_array.h ../../jparse/json_parse.h \
-    ../../jparse/util.h jnum_test.c
-jnum_chk.o: ../../dbg/dbg.h ../../dyn_array/../dbg/dbg.h \
-    ../../dyn_array/dyn_array.h ../../jparse/json_parse.h \
-    ../../jparse/json_util.h ../json_parse.h ../util.h jnum_chk.c \
-    jnum_chk.h
-jnum_test.o: ../../jparse/../dyn_array/../dbg/dbg.h \
-    ../../jparse/../dyn_array/dyn_array.h ../../jparse/json_parse.h \
-    ../../jparse/util.h jnum_test.c
 jnum_chk.o: ../../dbg/dbg.h ../../dyn_array/../dbg/dbg.h \
     ../../dyn_array/dyn_array.h ../../jparse/json_parse.h \
     ../../jparse/json_util.h ../json_parse.h ../util.h jnum_chk.c \
diff --git a/soup/Makefile b/soup/Makefile
--- a/soup/Makefile
+++ b/soup/Makefile
@@ -668,22 +668,23 @@ install: all
 depend: ${ALL_CSRC} all
 	@echo
 	@echo "${OUR_NAME}: make $@ starting"
-	@echo
 	@HAVE_INDEPEND="`type -P ${INDEPEND}`"; if [[ -z "$$HAVE_INDEPEND" ]]; then \
-	    echo 'The independ command could not be found.' 1>&2; \
-	    echo 'The independ command is required to run this rule.'; 1>&2; \
+	    echo '${OUR_NAME}: The independ command could not be found.' 1>&2; \
+	    echo '${OUR_NAME}: The independ command is required to perform: make $@'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo 'See the following GitHub repo for where to obtain independ:'; 1>&2; \
 	    echo ''; 1>&2; \
 	    echo '    https://github.com/lcn2/independ'; 1>&2; \
-	    echo ''; 1>&2; \
 	else \
-	    @${SED} -i.orig -n -e '1,/^### DO NOT CHANGE MANUALLY BEYOND THIS LINE/p' Makefile; \
+	    if ! ${GREP} -q '^### DO NOT CHANGE MANUALLY BEYOND THIS LINE$$' Makefile; then \
+	        echo "${OUR_NAME}: make $@ aborting, Makefile missing: ### DO NOT CHANGE MANUALLY BEYOND THIS LINE" 1>&2; \
+		exit 1; \
+	    fi; \
+	    ${SED} -i.orig -n -e '1,/^### DO NOT CHANGE MANUALLY BEYOND THIS LINE$$/p' Makefile; \
 	    ${CC} ${CFLAGS} -MM -I. -DMKIOCCCENTRY_USE ${ALL_CSRC} | ${INDEPEND} >> Makefile; \
 	    if ${CMP} -s Makefile.orig Makefile; then \
 		${RM} -f Makefile.orig; \
 	    else \
-		echo; \
 		echo "${OUR_NAME}: Makefile dependencies updated"; \
 		echo; \
 		echo "${OUR_NAME}: Previous version may be found in: Makefile.orig"; \
@@ -693,91 +694,6 @@ depend: ${ALL_CSRC} all
 	@echo "${OUR_NAME}: make $@ complete"
 
 ### DO NOT CHANGE MANUALLY BEYOND THIS LINE
-chk_sem_auth.o: ../jparse/../dyn_array/../dbg/dbg.h \
-    ../jparse/../dyn_array/dyn_array.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    chk_sem_auth.c chk_sem_auth.h
-chk_sem_info.o: ../jparse/../dyn_array/../dbg/dbg.h \
-    ../jparse/../dyn_array/dyn_array.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    chk_sem_info.c chk_sem_info.h
-chk_validate.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    chk_sem_auth.h chk_sem_info.h chk_validate.c chk_validate.h \
-    entry_time.h entry_util.h location.h
-entry_time.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    entry_time.c entry_time.h limit_ioccc.h version.h
-entry_util.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    entry_time.h entry_util.c entry_util.h limit_ioccc.h location.h \
-    version.h
-foo.o: ../dbg/dbg.h foo.c foo.h oebxergfB.h
-location.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h location.c \
-    location.h
-rule_count.o: ../iocccsize.h iocccsize_err.h rule_count.c
-sanity.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    limit_ioccc.h location.h sanity.c sanity.h utf8_posix_map.h version.h
-utf8_posix_map.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    limit_ioccc.h utf8_posix_map.c utf8_posix_map.h version.h
-chk_sem_auth.o: ../jparse/../dyn_array/../dbg/dbg.h \
-    ../jparse/../dyn_array/dyn_array.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    chk_sem_auth.c chk_sem_auth.h
-chk_sem_info.o: ../jparse/../dyn_array/../dbg/dbg.h \
-    ../jparse/../dyn_array/dyn_array.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    chk_sem_info.c chk_sem_info.h
-chk_validate.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    chk_sem_auth.h chk_sem_info.h chk_validate.c chk_validate.h \
-    entry_time.h entry_util.h location.h
-entry_time.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    entry_time.c entry_time.h limit_ioccc.h version.h
-entry_util.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    entry_time.h entry_util.c entry_util.h limit_ioccc.h location.h \
-    version.h
-foo.o: ../dbg/dbg.h foo.c foo.h oebxergfB.h
-location.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h location.c \
-    location.h
-rule_count.o: ../dbg/dbg.h ../iocccsize.h iocccsize_err.h limit_ioccc.h \
-    rule_count.c version.h
-sanity.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    limit_ioccc.h location.h sanity.c sanity.h utf8_posix_map.h version.h
-utf8_posix_map.o: ../dbg/dbg.h ../jparse/../dbg/dbg.h \
-    ../jparse/../dyn_array/../dbg/dbg.h ../jparse/../dyn_array/dyn_array.h \
-    ../jparse/jparse.h ../jparse/jparse.tab.h ../jparse/json_parse.h \
-    ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
-    limit_ioccc.h utf8_posix_map.c utf8_posix_map.h version.h
 chk_sem_auth.o: ../jparse/../dyn_array/../dbg/dbg.h \
     ../jparse/../dyn_array/dyn_array.h ../jparse/json_parse.h \
     ../jparse/json_sem.h ../jparse/json_util.h ../jparse/util.h \
