update from dbg, dyn_alloc and jparse repos.
Updated from repos via:

```sh
make all.recreate_clone && make all.update_from_clone
```

Performed `make release` to test the above under macOS.

diff --git a/jparse/test_jparse/Makefile b/jparse/test_jparse/Makefile
--- a/jparse/test_jparse/Makefile
+++ b/jparse/test_jparse/Makefile
@@ -293,7 +293,7 @@ SH_TARGETS=
 
 # program targets to make by all, installed by install, and removed by clobber
 #
-PROG_TARGETS= jnum_chk jnum_gen pr_jparse_test
+PROG_TARGETS= jnum_chk jnum_gen pr_jparse_test util_test
 
 # what to make by all but NOT to removed by clobber
 #
@@ -411,13 +411,16 @@ rebuild_jparse_err_files:
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ ending"
 
-test:
+test: util_test
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ starting"
 	${Q} if [[ ! -x ./run_jparse_tests.sh ]]; then \
 	    echo "${OUR_NAME}: ERROR: executable not found: ./run_jparse_tests.sh" 1>&2; \
 	    echo "${OUR_NAME}: ERROR: unable to perform complete test" 1>&2; \
 	    exit 1; \
+	elif [[ ! -x ./util_test ]]; then \
+	    echo "${OUR_NAME}: ERROR: executable not found: ./util_test" 1>&2; \
+	    echo "${OUR_NAME}: ERROR: unable to perform complete test" 1>&2; \
 	elif [[ ! -x ./jstr_test.sh ]]; then \
 	    echo "${OUR_NAME}: ERROR: executable not found: ./jstr_test.sh" 1>&2; \
 	    echo "${OUR_NAME}: ERROR: unable to perform complete test" 1>&2; \
@@ -439,6 +442,16 @@ test:
 	fi
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ ending"
+
+util_test.c: ../util.c
+	${Q} ${RM} ${RM_V} -f $@
+	${CP} -v -f $^ $@
+
+util_test.o: util_test.c
+	${CC} ${CFLAGS} -DUTIL_TEST util_test.c -c
+
+util_test: util_test.o ../libjparse.a
+	${CC} ${CFLAGS} $^ -o $@ -ldbg -ldyn_array
 
 # sequence exit codes
 #
@@ -667,6 +680,7 @@ uninstall:
 	${Q} ${RM} ${RM_V} -f ${DEST_DIR}/jnum_chk
 	${Q} ${RM} ${RM_V} -f ${DEST_DIR}/jnum_gen
 	${Q} ${RM} ${RM_V} -f ${DEST_DIR}/pr_jparse_test
+	${Q} ${RM} ${RM_V} -f ${DEST_DIR}/util_test
 	${S} echo
 	${S} echo "${OUR_NAME}: make $@ ending"
 
